// Package notifications provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package notifications

// Defines values for NotifyOverride.
const (
	NotifyOverrideAll     NotifyOverride = "all"
	NotifyOverrideDefault NotifyOverride = "default"
	NotifyOverrideFailure NotifyOverride = "failure"
	NotifyOverrideNone    NotifyOverride = "none"
)

// Valid indicates whether the value is a known member of the NotifyOverride enum.
func (e NotifyOverride) Valid() bool {
	switch e {
	case NotifyOverrideAll:
		return true
	case NotifyOverrideDefault:
		return true
	case NotifyOverrideFailure:
		return true
	case NotifyOverrideNone:
		return true
	default:
		return false
	}
}

// Defines values for NotifyPreviewOverride.
const (
	NotifyPreviewOverrideDefault NotifyPreviewOverride = "default"
	NotifyPreviewOverrideFalse   NotifyPreviewOverride = "false"
	NotifyPreviewOverrideTrue    NotifyPreviewOverride = "true"
)

// Valid indicates whether the value is a known member of the NotifyPreviewOverride enum.
func (e NotifyPreviewOverride) Valid() bool {
	switch e {
	case NotifyPreviewOverrideDefault:
		return true
	case NotifyPreviewOverrideFalse:
		return true
	case NotifyPreviewOverrideTrue:
		return true
	default:
		return false
	}
}

// Defines values for NotifySettingV2.
const (
	All     NotifySettingV2 = "all"
	Failure NotifySettingV2 = "failure"
	None    NotifySettingV2 = "none"
)

// Valid indicates whether the value is a known member of the NotifySettingV2 enum.
func (e NotifySettingV2) Valid() bool {
	switch e {
	case All:
		return true
	case Failure:
		return true
	case None:
		return true
	default:
		return false
	}
}

// NotificationOverride defines model for notificationOverride.
type NotificationOverride struct {
	NotificationsToSend         NotifyOverride        `json:"notificationsToSend"`
	PreviewNotificationsEnabled NotifyPreviewOverride `json:"previewNotificationsEnabled"`
	ServiceId                   string                `json:"serviceId"`
}

// NotificationServiceOverride defines model for notificationServiceOverride.
type NotificationServiceOverride struct {
	NotificationsToSend         NotifyOverride        `json:"notificationsToSend"`
	PreviewNotificationsEnabled NotifyPreviewOverride `json:"previewNotificationsEnabled"`
	ServiceId                   string                `json:"serviceId"`
}

// NotificationServiceOverridePATCH defines model for notificationServiceOverridePATCH.
type NotificationServiceOverridePATCH struct {
	NotificationsToSend         *NotifyOverride        `json:"notificationsToSend,omitempty"`
	PreviewNotificationsEnabled *NotifyPreviewOverride `json:"previewNotificationsEnabled,omitempty"`
}

// NotificationSetting defines model for notificationSetting.
type NotificationSetting struct {
	EmailEnabled                bool            `json:"emailEnabled"`
	NotificationsToSend         NotifySettingV2 `json:"notificationsToSend"`
	OwnerId                     string          `json:"ownerId"`
	PreviewNotificationsEnabled bool            `json:"previewNotificationsEnabled"`
	SlackEnabled                bool            `json:"slackEnabled"`
}

// NotificationSettingPATCH defines model for notificationSettingPATCH.
type NotificationSettingPATCH struct {
	EmailEnabled                *bool            `json:"emailEnabled,omitempty"`
	NotificationsToSend         *NotifySettingV2 `json:"notificationsToSend,omitempty"`
	PreviewNotificationsEnabled *bool            `json:"previewNotificationsEnabled,omitempty"`
}

// NotifyOverride defines model for notifyOverride.
type NotifyOverride string

// NotifyPreviewOverride defines model for notifyPreviewOverride.
type NotifyPreviewOverride string

// NotifySettingV2 defines model for notifySettingV2.
type NotifySettingV2 string
