// Package sandboxes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package sandboxes

import (
	"time"
)

// Defines values for ExecutionOperation.
const (
	Download ExecutionOperation = "download"
	Stream   ExecutionOperation = "stream"
	Sync     ExecutionOperation = "sync"
	Upload   ExecutionOperation = "upload"
)

// Valid indicates whether the value is a known member of the ExecutionOperation enum.
func (e ExecutionOperation) Valid() bool {
	switch e {
	case Download:
		return true
	case Stream:
		return true
	case Sync:
		return true
	case Upload:
		return true
	default:
		return false
	}
}

// Defines values for ExecutionType.
const (
	Files ExecutionType = "files"
	Runs  ExecutionType = "runs"
)

// Valid indicates whether the value is a known member of the ExecutionType enum.
func (e ExecutionType) Valid() bool {
	switch e {
	case Files:
		return true
	case Runs:
		return true
	default:
		return false
	}
}

// Defines values for SandboxFileEntryType.
const (
	Directory SandboxFileEntryType = "directory"
	File      SandboxFileEntryType = "file"
	Symlink   SandboxFileEntryType = "symlink"
)

// Valid indicates whether the value is a known member of the SandboxFileEntryType enum.
func (e SandboxFileEntryType) Valid() bool {
	switch e {
	case Directory:
		return true
	case File:
		return true
	case Symlink:
		return true
	default:
		return false
	}
}

// Defines values for SandboxLifecycleEventType.
const (
	SandboxLifecycleEventTypeCreating   SandboxLifecycleEventType = "creating"
	SandboxLifecycleEventTypeErrored    SandboxLifecycleEventType = "errored"
	SandboxLifecycleEventTypeResuming   SandboxLifecycleEventType = "resuming"
	SandboxLifecycleEventTypeRunning    SandboxLifecycleEventType = "running"
	SandboxLifecycleEventTypeSuspended  SandboxLifecycleEventType = "suspended"
	SandboxLifecycleEventTypeTerminated SandboxLifecycleEventType = "terminated"
)

// Valid indicates whether the value is a known member of the SandboxLifecycleEventType enum.
func (e SandboxLifecycleEventType) Valid() bool {
	switch e {
	case SandboxLifecycleEventTypeCreating:
		return true
	case SandboxLifecycleEventTypeErrored:
		return true
	case SandboxLifecycleEventTypeResuming:
		return true
	case SandboxLifecycleEventTypeRunning:
		return true
	case SandboxLifecycleEventTypeSuspended:
		return true
	case SandboxLifecycleEventTypeTerminated:
		return true
	default:
		return false
	}
}

// Defines values for SandboxLogEventStream.
const (
	Stderr SandboxLogEventStream = "stderr"
	Stdout SandboxLogEventStream = "stdout"
)

// Valid indicates whether the value is a known member of the SandboxLogEventStream enum.
func (e SandboxLogEventStream) Valid() bool {
	switch e {
	case Stderr:
		return true
	case Stdout:
		return true
	default:
		return false
	}
}

// Defines values for SandboxNetworkPolicyDefault.
const (
	AllowAll SandboxNetworkPolicyDefault = "allow-all"
	DenyAll  SandboxNetworkPolicyDefault = "deny-all"
)

// Valid indicates whether the value is a known member of the SandboxNetworkPolicyDefault enum.
func (e SandboxNetworkPolicyDefault) Valid() bool {
	switch e {
	case AllowAll:
		return true
	case DenyAll:
		return true
	default:
		return false
	}
}

// Defines values for SandboxPlan.
const (
	Pro      SandboxPlan = "pro"
	Standard SandboxPlan = "standard"
	Starter  SandboxPlan = "starter"
)

// Valid indicates whether the value is a known member of the SandboxPlan enum.
func (e SandboxPlan) Valid() bool {
	switch e {
	case Pro:
		return true
	case Standard:
		return true
	case Starter:
		return true
	default:
		return false
	}
}

// Defines values for SandboxStatus.
const (
	SandboxStatusCreating   SandboxStatus = "creating"
	SandboxStatusErrored    SandboxStatus = "errored"
	SandboxStatusResuming   SandboxStatus = "resuming"
	SandboxStatusRunning    SandboxStatus = "running"
	SandboxStatusSuspended  SandboxStatus = "suspended"
	SandboxStatusTerminated SandboxStatus = "terminated"
)

// Valid indicates whether the value is a known member of the SandboxStatus enum.
func (e SandboxStatus) Valid() bool {
	switch e {
	case SandboxStatusCreating:
		return true
	case SandboxStatusErrored:
		return true
	case SandboxStatusResuming:
		return true
	case SandboxStatusRunning:
		return true
	case SandboxStatusSuspended:
		return true
	case SandboxStatusTerminated:
		return true
	default:
		return false
	}
}

// Execution One recorded sandbox execution (a command run or file transfer).
// `startedAt` is the token provisioning time. `command` may be present
// while the execution is in flight (recorded at token mint). `stoppedAt`
// and `exitCode` are absent until a status report or sandbox finalization.
type Execution struct {
	// Command The execution target. For runs, the truncated command; for file transfers, the target file path.
	Command *string `json:"command,omitempty"`

	// ExitCode Example: 0
	ExitCode *int `json:"exitCode,omitempty"`

	// Id Example: exe-cph1rs3idesc73a2b2mg
	Id        ExecutionId        `json:"id"`
	Operation ExecutionOperation `json:"operation"`

	// SandboxId Example: sbx-1cd4gcph1rs3idesc73a2b2mg
	SandboxId SandboxId `json:"sandboxId"`

	// StartedAt Example: 2026-08-01T10:00:00Z
	StartedAt time.Time `json:"startedAt"`

	// StoppedAt Example: 2026-08-01T10:05:00Z
	StoppedAt *time.Time    `json:"stoppedAt,omitempty"`
	Type      ExecutionType `json:"type"`

	// UserId The ID of the user the execution token was minted for.
	//
	// Example: usr-cph1rs3idesc73a2b2mg
	UserId string `json:"userId"`
}

// ExecutionOperation defines model for Execution.Operation.
type ExecutionOperation string

// ExecutionType defines model for Execution.Type.
type ExecutionType string

// ExecutionId Example: exe-cph1rs3idesc73a2b2mg
type ExecutionId = string

// Sandbox defines model for sandbox.
type Sandbox struct {
	// CreatedAt Example: 2026-04-01T18:30:00Z
	CreatedAt time.Time `json:"createdAt"`

	// Id Example: sbx-1cd4gcph1rs3idesc73a2b2mg
	Id            SandboxId            `json:"id"`
	NetworkPolicy SandboxNetworkPolicy `json:"networkPolicy"`

	// Plan Compute plan. Sizing matches Workflow plans of the same name.
	Plan SandboxPlan `json:"plan"`

	// Region Region the sandbox is running in.
	//
	// Example: oregon
	Region string        `json:"region"`
	Status SandboxStatus `json:"status"`

	// TerminatedAt When the sandbox was terminated, or null.
	TerminatedAt *time.Time `json:"terminatedAt,omitempty"`

	// TimeoutSeconds Maximum sandbox lifetime in seconds.
	//
	// Example: 7200
	TimeoutSeconds int `json:"timeoutSeconds"`
}

// SandboxConnectRequest Optional body when minting a run connect token. `command` is stored on
// the exec timeline (truncated to 4KB); the full command is still sent
// to the sandbox proxy when executing.
type SandboxConnectRequest struct {
	// Command Command text for the sandbox event timeline.
	Command *string `json:"command,omitempty"`
}

// SandboxConnectResponse A minted connect token and the sandbox-proxy endpoint to invoke with it.
// Send the request (and body, where the operation takes one) to `uri`
// using `method`, with `token` as a bearer credential.
type SandboxConnectResponse struct {
	// ExecutionId Identifier for this execution.
	//
	// Example: exe-cph1rs3idesc73a2b2mg
	ExecutionId string `json:"executionId"`

	// ExpiresAt When `token` stops being valid. Start the run before this time.
	//
	// Example: 2026-07-10T12:00:00Z
	ExpiresAt time.Time `json:"expiresAt"`

	// Method HTTP method to use against `uri`.
	//
	// Example: POST
	Method string `json:"method"`

	// Token Short-lived bearer token authorizing exactly this operation against the sandbox.
	Token string `json:"token"`

	// Uri The sandbox-proxy endpoint to invoke.
	//
	// Example: https://sbx-abc123.oregon.sandbox.onrender.com/runs/stream
	Uri string `json:"uri"`
}

// SandboxDirectoryListing Directory listing response.
type SandboxDirectoryListing struct {
	Entries []SandboxFileEntry `json:"entries"`

	// Path The absolute path that was listed.
	//
	// Example: /app
	Path string `json:"path"`
}

// SandboxExecUpdateRequest Client-reported completion of a sandbox execution.
type SandboxExecUpdateRequest struct {
	// ExitCode Process exit code observed by the client.
	ExitCode *int `json:"exitCode,omitempty"`
}

// SandboxExecUpdateResponse Updated sandbox execution after a client update.
type SandboxExecUpdateResponse struct {
	Command   *string    `json:"command,omitempty"`
	ExecId    string     `json:"execId"`
	ExitCode  *int       `json:"exitCode,omitempty"`
	Operation string     `json:"operation"`
	SandboxId string     `json:"sandboxId"`
	StartedAt time.Time  `json:"startedAt"`
	StoppedAt *time.Time `json:"stoppedAt,omitempty"`
	Type      string     `json:"type"`
}

// SandboxFileEntry A file or directory entry in a sandbox filesystem listing.
type SandboxFileEntry struct {
	// ModifiedAt Last-modified timestamp.
	ModifiedAt time.Time `json:"modifiedAt"`

	// Name File or directory name (basename, not full path).
	//
	// Example: main.py
	Name string `json:"name"`

	// Size Size in bytes. 0 for directories and symlinks.
	//
	// Example: 2048
	Size int `json:"size"`

	// Target Symlink target path. Present only when type is `symlink`.
	Target *string `json:"target,omitempty"`

	// Type Entry type.
	Type SandboxFileEntryType `json:"type"`
}

// SandboxFileEntryType Entry type.
type SandboxFileEntryType string

// SandboxGroup defines model for sandboxGroup.
type SandboxGroup struct {
	// ConcurrencyLimit Effective maximum number of concurrently active (non-terminated) sandboxes allowed in this group.
	ConcurrencyLimit int `json:"concurrencyLimit"`

	// CreatedAt Example: 2026-07-02T18:30:00Z
	CreatedAt time.Time `json:"createdAt"`

	// EnvironmentId Environment this group is bound to.
	EnvironmentId *string `json:"environmentId,omitempty"`

	// Id Example: sbg-cph1rs3idesc73a2b2mg
	Id SandboxGroupId `json:"id"`

	// IsDefault Whether this is the workspace's default group. Exactly one group per workspace is the default.
	IsDefault bool `json:"isDefault"`

	// Name Human-friendly name for the group.
	//
	// Example: Default
	Name string `json:"name"`

	// OwnerId The ID of the workspace this group belongs to.
	//
	// Example: tea-cph1rs3idesc73a2b2mg
	OwnerId string `json:"ownerId"`

	// Region Render region the group operates in.
	//
	// Example: oregon
	Region string `json:"region"`

	// UpdatedAt Example: 2026-07-02T18:30:00Z
	UpdatedAt time.Time `json:"updatedAt"`
}

// SandboxGroupId Example: sbg-cph1rs3idesc73a2b2mg
type SandboxGroupId = string

// SandboxId Example: sbx-1cd4gcph1rs3idesc73a2b2mg
type SandboxId = string

// SandboxLifecycleEvent A lifecycle event from the sandbox logs stream.
type SandboxLifecycleEvent struct {
	At   time.Time                 `json:"at"`
	Type SandboxLifecycleEventType `json:"type"`
}

// SandboxLifecycleEventType defines model for SandboxLifecycleEvent.Type.
type SandboxLifecycleEventType string

// SandboxLogEvent A log event from the sandbox logs stream.
type SandboxLogEvent struct {
	At time.Time `json:"at"`

	// Data Output chunk.
	Data string `json:"data"`

	// ExecId Groups output by command for the event timeline. Absent for system-level output (container startup, OOM, etc.).
	//
	// Example: exe-cph1rs3idesc73a2b2mg
	ExecId *string               `json:"execId,omitempty"`
	Stream SandboxLogEventStream `json:"stream"`
}

// SandboxLogEventStream defines model for SandboxLogEvent.Stream.
type SandboxLogEventStream string

// SandboxNetworkPolicy defines model for sandboxNetworkPolicy.
type SandboxNetworkPolicy struct {
	// Default Default action for outbound traffic.
	Default SandboxNetworkPolicyDefault `json:"default"`
}

// SandboxNetworkPolicyDefault Default action for outbound traffic.
type SandboxNetworkPolicyDefault string

// SandboxPOST defines model for sandboxPOST.
type SandboxPOST struct {
	// Env Inline environment variables injected into the sandbox at creation.
	Env           *map[string]string    `json:"env,omitempty"`
	NetworkPolicy *SandboxNetworkPolicy `json:"networkPolicy,omitempty"`

	// OwnerId The ID of the workspace the sandbox belongs to.
	OwnerId string       `json:"ownerId"`
	Plan    *SandboxPlan `json:"plan,omitempty"`

	// Region Render region. Defaults to the workspace default.
	Region *string `json:"region,omitempty"`

	// TimeoutSeconds Maximum sandbox lifetime in seconds. Sandbox is terminated when reached.
	TimeoutSeconds *int `json:"timeoutSeconds,omitempty"`
}

// SandboxPlan Compute plan. Sizing matches Workflow plans of the same name.
type SandboxPlan string

// SandboxStatus defines model for sandboxStatus.
type SandboxStatus string

// ExecId Example: exe-cph1rs3idesc73a2b2mg
type ExecId = ExecutionId

// OwnerId defines model for ownerId.
type OwnerId = string
