// Package sandboxes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package sandboxes

import (
	"time"
)

// Defines values for SandboxExecStreamOutputEventStream.
const (
	SandboxExecStreamOutputEventStreamStderr SandboxExecStreamOutputEventStream = "stderr"
	SandboxExecStreamOutputEventStreamStdout SandboxExecStreamOutputEventStream = "stdout"
)

// Valid indicates whether the value is a known member of the SandboxExecStreamOutputEventStream enum.
func (e SandboxExecStreamOutputEventStream) Valid() bool {
	switch e {
	case SandboxExecStreamOutputEventStreamStderr:
		return true
	case SandboxExecStreamOutputEventStreamStdout:
		return true
	default:
		return false
	}
}

// Defines values for SandboxFileEntryType.
const (
	Directory SandboxFileEntryType = "directory"
	File      SandboxFileEntryType = "file"
	Symlink   SandboxFileEntryType = "symlink"
)

// Valid indicates whether the value is a known member of the SandboxFileEntryType enum.
func (e SandboxFileEntryType) Valid() bool {
	switch e {
	case Directory:
		return true
	case File:
		return true
	case Symlink:
		return true
	default:
		return false
	}
}

// Defines values for SandboxLifecycleEventType.
const (
	SandboxLifecycleEventTypeCreating   SandboxLifecycleEventType = "creating"
	SandboxLifecycleEventTypeErrored    SandboxLifecycleEventType = "errored"
	SandboxLifecycleEventTypeResuming   SandboxLifecycleEventType = "resuming"
	SandboxLifecycleEventTypeRunning    SandboxLifecycleEventType = "running"
	SandboxLifecycleEventTypeSuspended  SandboxLifecycleEventType = "suspended"
	SandboxLifecycleEventTypeTerminated SandboxLifecycleEventType = "terminated"
)

// Valid indicates whether the value is a known member of the SandboxLifecycleEventType enum.
func (e SandboxLifecycleEventType) Valid() bool {
	switch e {
	case SandboxLifecycleEventTypeCreating:
		return true
	case SandboxLifecycleEventTypeErrored:
		return true
	case SandboxLifecycleEventTypeResuming:
		return true
	case SandboxLifecycleEventTypeRunning:
		return true
	case SandboxLifecycleEventTypeSuspended:
		return true
	case SandboxLifecycleEventTypeTerminated:
		return true
	default:
		return false
	}
}

// Defines values for SandboxLogEventStream.
const (
	SandboxLogEventStreamStderr SandboxLogEventStream = "stderr"
	SandboxLogEventStreamStdout SandboxLogEventStream = "stdout"
)

// Valid indicates whether the value is a known member of the SandboxLogEventStream enum.
func (e SandboxLogEventStream) Valid() bool {
	switch e {
	case SandboxLogEventStreamStderr:
		return true
	case SandboxLogEventStreamStdout:
		return true
	default:
		return false
	}
}

// Defines values for SandboxNetworkPolicyDefault.
const (
	AllowAll SandboxNetworkPolicyDefault = "allow-all"
	DenyAll  SandboxNetworkPolicyDefault = "deny-all"
)

// Valid indicates whether the value is a known member of the SandboxNetworkPolicyDefault enum.
func (e SandboxNetworkPolicyDefault) Valid() bool {
	switch e {
	case AllowAll:
		return true
	case DenyAll:
		return true
	default:
		return false
	}
}

// Defines values for SandboxPlan.
const (
	Pro      SandboxPlan = "pro"
	Standard SandboxPlan = "standard"
	Starter  SandboxPlan = "starter"
)

// Valid indicates whether the value is a known member of the SandboxPlan enum.
func (e SandboxPlan) Valid() bool {
	switch e {
	case Pro:
		return true
	case Standard:
		return true
	case Starter:
		return true
	default:
		return false
	}
}

// Defines values for SandboxStatus.
const (
	SandboxStatusCreating   SandboxStatus = "creating"
	SandboxStatusErrored    SandboxStatus = "errored"
	SandboxStatusResuming   SandboxStatus = "resuming"
	SandboxStatusRunning    SandboxStatus = "running"
	SandboxStatusSuspended  SandboxStatus = "suspended"
	SandboxStatusTerminated SandboxStatus = "terminated"
)

// Valid indicates whether the value is a known member of the SandboxStatus enum.
func (e SandboxStatus) Valid() bool {
	switch e {
	case SandboxStatusCreating:
		return true
	case SandboxStatusErrored:
		return true
	case SandboxStatusResuming:
		return true
	case SandboxStatusRunning:
		return true
	case SandboxStatusSuspended:
		return true
	case SandboxStatusTerminated:
		return true
	default:
		return false
	}
}

// Sandbox defines model for sandbox.
type Sandbox struct {
	CreatedAt     time.Time            `json:"createdAt"`
	Id            SandboxId            `json:"id"`
	NetworkPolicy SandboxNetworkPolicy `json:"networkPolicy"`

	// Plan Compute plan. Sizing matches Workflow plans of the same name.
	Plan SandboxPlan `json:"plan"`

	// Region Region the sandbox is running in.
	Region string        `json:"region"`
	Status SandboxStatus `json:"status"`

	// TerminatedAt When the sandbox was terminated, or null.
	TerminatedAt *time.Time `json:"terminatedAt,omitempty"`

	// TimeoutSeconds Maximum sandbox lifetime in seconds.
	TimeoutSeconds int `json:"timeoutSeconds"`
}

// SandboxDirectoryListing Directory listing response.
type SandboxDirectoryListing struct {
	Entries []SandboxFileEntry `json:"entries"`

	// Path The absolute path that was listed.
	Path string `json:"path"`
}

// SandboxExecStreamErrorEvent Payload for terminal `event: error` in a sandbox exec SSE stream when a runtime or transport failure occurs after streaming has started.
type SandboxExecStreamErrorEvent struct {
	// Message Error message.
	Message string `json:"message"`

	// Status HTTP-style status code for the terminal streaming error.
	Status int `json:"status"`
}

// SandboxExecStreamExitEvent Payload for terminal `event: exit` in a sandbox exec SSE stream. Non-zero process exit codes are reported here rather than as HTTP errors.
type SandboxExecStreamExitEvent struct {
	// ExitCode Process exit code.
	ExitCode int `json:"exit_code"`
}

// SandboxExecStreamOutputEvent Payload for `event: output` in a sandbox exec SSE stream.
type SandboxExecStreamOutputEvent struct {
	// Data Output chunk.
	Data string `json:"data"`

	// Stream Output stream that produced this chunk.
	Stream SandboxExecStreamOutputEventStream `json:"stream"`
}

// SandboxExecStreamOutputEventStream Output stream that produced this chunk.
type SandboxExecStreamOutputEventStream string

// SandboxExecSyncRequest Body of the synchronous exec endpoint.
type SandboxExecSyncRequest struct {
	// Command Bash command to run. Passed to `bash -c` in the sandbox.
	Command string `json:"command"`
}

// SandboxExecSyncResponse Response from the synchronous exec endpoint. Returned after the command exits.
type SandboxExecSyncResponse struct {
	// ExitCode Process exit code.
	ExitCode int `json:"exitCode"`

	// Stderr Captured stderr.
	Stderr string `json:"stderr"`

	// Stdout Captured stdout.
	Stdout string `json:"stdout"`
}

// SandboxFileEntry A file or directory entry in a sandbox filesystem listing.
type SandboxFileEntry struct {
	// ModifiedAt Last-modified timestamp.
	ModifiedAt time.Time `json:"modifiedAt"`

	// Name File or directory name (basename, not full path).
	Name string `json:"name"`

	// Size Size in bytes. 0 for directories and symlinks.
	Size int `json:"size"`

	// Target Symlink target path. Present only when type is `symlink`.
	Target *string `json:"target,omitempty"`

	// Type Entry type.
	Type SandboxFileEntryType `json:"type"`
}

// SandboxFileEntryType Entry type.
type SandboxFileEntryType string

// SandboxId defines model for sandboxId.
type SandboxId = string

// SandboxLifecycleEvent A lifecycle event from the sandbox logs stream.
type SandboxLifecycleEvent struct {
	At   time.Time                 `json:"at"`
	Type SandboxLifecycleEventType `json:"type"`
}

// SandboxLifecycleEventType defines model for SandboxLifecycleEvent.Type.
type SandboxLifecycleEventType string

// SandboxLogEvent A log event from the sandbox logs stream.
type SandboxLogEvent struct {
	At time.Time `json:"at"`

	// Data Output chunk.
	Data string `json:"data"`

	// ExecId Groups output by command for the event timeline. Absent for system-level output (container startup, OOM, etc.).
	ExecId *string               `json:"execId,omitempty"`
	Stream SandboxLogEventStream `json:"stream"`
}

// SandboxLogEventStream defines model for SandboxLogEvent.Stream.
type SandboxLogEventStream string

// SandboxNetworkPolicy defines model for sandboxNetworkPolicy.
type SandboxNetworkPolicy struct {
	// Default Default action for outbound traffic.
	Default SandboxNetworkPolicyDefault `json:"default"`
}

// SandboxNetworkPolicyDefault Default action for outbound traffic.
type SandboxNetworkPolicyDefault string

// SandboxPOST defines model for sandboxPOST.
type SandboxPOST struct {
	NetworkPolicy *SandboxNetworkPolicy `json:"networkPolicy,omitempty"`

	// OwnerId The ID of the workspace the sandbox belongs to.
	OwnerId string       `json:"ownerId"`
	Plan    *SandboxPlan `json:"plan,omitempty"`

	// Region Render region. Defaults to the workspace default.
	Region *string `json:"region,omitempty"`

	// TimeoutSeconds Maximum sandbox lifetime in seconds. Sandbox is terminated when reached.
	TimeoutSeconds *int `json:"timeoutSeconds,omitempty"`
}

// SandboxPlan Compute plan. Sizing matches Workflow plans of the same name.
type SandboxPlan string

// SandboxStatus defines model for sandboxStatus.
type SandboxStatus string
