// Package webhooks provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package webhooks

import (
	externalRef5 "terraform-provider-render/internal/client/eventtypes"
)

// EventTypes The event types that will trigger the webhook
type EventTypes = []externalRef5.EventType

// Webhook defines model for webhook.
type Webhook struct {
	Enabled bool `json:"enabled"`

	// EventTypes The event types that will trigger the webhook
	EventTypes EventTypes `json:"eventTypes"`
	Id         string     `json:"id"`
	Secret     string     `json:"secret"`
	Url        string     `json:"url"`
}

// WebhookPOSTInput defines model for webhookPOSTInput.
type WebhookPOSTInput struct {
	Enabled bool `json:"enabled"`

	// EventTypes The event types that will trigger the webhook
	EventTypes EventTypes `json:"eventTypes"`

	// OwnerId The ID of the owner (team or personal user) whose resources should be returned
	OwnerId string `json:"ownerId"`
	Url     string `json:"url"`
}
