// Package webhooks provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package webhooks

import (
	"time"

	externalRef8 "terraform-provider-render/internal/client/eventtypes"
)

// EventFilter The event types that will trigger the webhook. An empty list means all event types will trigger the webhook.
type EventFilter = []externalRef8.EventType

// Webhook defines model for webhook.
type Webhook struct {
	Enabled bool `json:"enabled"`

	// EventFilter The event types that will trigger the webhook. An empty list means all event types will trigger the webhook.
	EventFilter EventFilter `json:"eventFilter"`

	// Id Example: whk-d04m9b1r0fns73ckp94f
	Id     WebhookId `json:"id"`
	Name   string    `json:"name"`
	Secret string    `json:"secret"`
	Url    string    `json:"url"`
}

// WebhookEvent defines model for webhookEvent.
type WebhookEvent struct {
	// Error error is populated when an error occurs without a response such as a timeout
	Error *string `json:"error,omitempty"`

	// EventId the id of the event that triggered the webhook
	EventId   string                 `json:"eventId"`
	EventType externalRef8.EventType `json:"eventType"`

	// Id the id of the webhook event
	Id           string    `json:"id"`
	ResponseBody *string   `json:"responseBody,omitempty"`
	SentAt       time.Time `json:"sentAt"`
	StatusCode   *int      `json:"statusCode,omitempty"`
}

// WebhookId Example: whk-d04m9b1r0fns73ckp94f
type WebhookId = string

// WebhookPATCHInput defines model for webhookPATCHInput.
type WebhookPATCHInput struct {
	Enabled *bool `json:"enabled,omitempty"`

	// EventFilter The event types that will trigger the webhook. An empty list means all event types will trigger the webhook.
	EventFilter *EventFilter `json:"eventFilter,omitempty"`
	Name        *string      `json:"name,omitempty"`
	Url         *string      `json:"url,omitempty"`
}

// WebhookPOSTInput defines model for webhookPOSTInput.
type WebhookPOSTInput struct {
	Enabled bool `json:"enabled"`

	// EventFilter The event types that will trigger the webhook. An empty list means all event types will trigger the webhook.
	EventFilter EventFilter `json:"eventFilter"`
	Name        string      `json:"name"`

	// OwnerId The ID of the owner (team or personal user) whose resources should be returned
	OwnerId string `json:"ownerId"`
	Url     string `json:"url"`
}

// SentAfterParam defines model for sentAfterParam.
type SentAfterParam = time.Time

// SentBeforeParam defines model for sentBeforeParam.
type SentBeforeParam = time.Time

// WebhookIdParam Example: whk-d04m9b1r0fns73ckp94f
type WebhookIdParam = WebhookId
