// Package storage provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package storage

import (
	"time"
)

// GetObjectOutput defines model for getObjectOutput.
type GetObjectOutput struct {
	// ExpiresAt The time at which the presigned URL expires (ISO 8601 format)
	//
	// Example: 2024-01-15T12:30:00Z
	ExpiresAt time.Time `json:"expiresAt"`

	// Url Presigned URL for downloading the object
	//
	// Example: https://example-bucket.s3.amazonaws.com/presigned-get-url
	Url string `json:"url"`
}

// ListObjectsResponse defines model for listObjectsResponse.
type ListObjectsResponse struct {
	// HasNext Whether there are more results after this page.
	HasNext bool               `json:"hasNext"`
	Items   []ObjectWithCursor `json:"items"`

	// NextCursor Cursor to fetch the next page. Only present when hasNext is true.
	NextCursor *string `json:"nextCursor,omitempty"`
}

// ObjectMetadata defines model for objectMetadata.
type ObjectMetadata struct {
	// Key The object's key
	//
	// Example: workflow-data/task-output.json
	Key string `json:"key"`

	// LastModified When the object was last modified (ISO 8601)
	//
	// Example: 2026-01-15T12:30:00Z
	LastModified time.Time `json:"lastModified"`

	// SizeBytes Size of the object in bytes
	//
	// Example: 1048576
	SizeBytes int64 `json:"sizeBytes"`
}

// ObjectWithCursor defines model for objectWithCursor.
type ObjectWithCursor struct {
	Cursor string         `json:"cursor"`
	Object ObjectMetadata `json:"object"`
}

// PutObjectInput defines model for putObjectInput.
type PutObjectInput struct {
	// SizeBytes The size of the object in bytes.
	//
	// Example: 1048576
	SizeBytes int64 `json:"sizeBytes"`
}

// PutObjectOutput defines model for putObjectOutput.
type PutObjectOutput struct {
	// ExpiresAt The time at which the presigned URL expires (ISO 8601 format)
	//
	// Example: 2024-01-15T12:30:00Z
	ExpiresAt time.Time `json:"expiresAt"`

	// MaxSizeBytes The maximum size of the object in bytes
	//
	// Example: 1048576
	MaxSizeBytes int64 `json:"maxSizeBytes"`

	// Url Presigned URL for uploading the object
	//
	// Example: https://example-bucket.s3.amazonaws.com/presigned-put-url
	Url string `json:"url"`
}

// ObjectKeyPathParam defines model for objectKeyPathParam.
type ObjectKeyPathParam = string
