// Package postgres provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package postgres

import (
	"time"
)

// Defines values for PostgresPlans.
const (
	Accelerated1024gb PostgresPlans = "accelerated_1024gb"
	Accelerated128gb  PostgresPlans = "accelerated_128gb"
	Accelerated16gb   PostgresPlans = "accelerated_16gb"
	Accelerated256gb  PostgresPlans = "accelerated_256gb"
	Accelerated32gb   PostgresPlans = "accelerated_32gb"
	Accelerated384gb  PostgresPlans = "accelerated_384gb"
	Accelerated512gb  PostgresPlans = "accelerated_512gb"
	Accelerated64gb   PostgresPlans = "accelerated_64gb"
	Accelerated768gb  PostgresPlans = "accelerated_768gb"
	Basic1gb          PostgresPlans = "basic_1gb"
	Basic256mb        PostgresPlans = "basic_256mb"
	Basic4gb          PostgresPlans = "basic_4gb"
	Custom            PostgresPlans = "custom"
	Free              PostgresPlans = "free"
	Pro               PostgresPlans = "pro"
	Pro128gb          PostgresPlans = "pro_128gb"
	Pro16gb           PostgresPlans = "pro_16gb"
	Pro192gb          PostgresPlans = "pro_192gb"
	Pro256gb          PostgresPlans = "pro_256gb"
	Pro32gb           PostgresPlans = "pro_32gb"
	Pro384gb          PostgresPlans = "pro_384gb"
	Pro4gb            PostgresPlans = "pro_4gb"
	Pro512gb          PostgresPlans = "pro_512gb"
	Pro64gb           PostgresPlans = "pro_64gb"
	Pro8gb            PostgresPlans = "pro_8gb"
	ProPlus           PostgresPlans = "pro_plus"
	Standard          PostgresPlans = "standard"
	Starter           PostgresPlans = "starter"
)

// Valid indicates whether the value is a known member of the PostgresPlans enum.
func (e PostgresPlans) Valid() bool {
	switch e {
	case Accelerated1024gb:
		return true
	case Accelerated128gb:
		return true
	case Accelerated16gb:
		return true
	case Accelerated256gb:
		return true
	case Accelerated32gb:
		return true
	case Accelerated384gb:
		return true
	case Accelerated512gb:
		return true
	case Accelerated64gb:
		return true
	case Accelerated768gb:
		return true
	case Basic1gb:
		return true
	case Basic256mb:
		return true
	case Basic4gb:
		return true
	case Custom:
		return true
	case Free:
		return true
	case Pro:
		return true
	case Pro128gb:
		return true
	case Pro16gb:
		return true
	case Pro192gb:
		return true
	case Pro256gb:
		return true
	case Pro32gb:
		return true
	case Pro384gb:
		return true
	case Pro4gb:
		return true
	case Pro512gb:
		return true
	case Pro64gb:
		return true
	case Pro8gb:
		return true
	case ProPlus:
		return true
	case Standard:
		return true
	case Starter:
		return true
	default:
		return false
	}
}

// Defines values for RecoveryInfoRecoveryStatus.
const (
	AVAILABLE      RecoveryInfoRecoveryStatus = "AVAILABLE"
	BACKUPNOTREADY RecoveryInfoRecoveryStatus = "BACKUP_NOT_READY"
	NOTAVAILABLE   RecoveryInfoRecoveryStatus = "NOT_AVAILABLE"
)

// Valid indicates whether the value is a known member of the RecoveryInfoRecoveryStatus enum.
func (e RecoveryInfoRecoveryStatus) Valid() bool {
	switch e {
	case AVAILABLE:
		return true
	case BACKUPNOTREADY:
		return true
	case NOTAVAILABLE:
		return true
	default:
		return false
	}
}

// CredentialCreateInput defines model for credentialCreateInput.
type CredentialCreateInput struct {
	// Username Name of the new user.
	Username string `json:"username"`
}

// PostgresAvailableParameterOverride defines model for postgresAvailableParameterOverride.
type PostgresAvailableParameterOverride struct {
	Description string    `json:"description"`
	Examples    *[]string `json:"examples,omitempty"`

	// MaxValue The maximum value allowed for numeric parameters.
	MaxValue *float32 `json:"maxValue,omitempty"`

	// MinValue The minimum value allowed for numeric parameters.
	MinValue *float32 `json:"minValue,omitempty"`
	Name     string   `json:"name"`

	// RequiresRestart Whether setting this parameter requires a restart to take effect.
	RequiresRestart bool `json:"requiresRestart"`
}

// PostgresAvailableParameterOverridesResult defines model for postgresAvailableParameterOverridesResult.
type PostgresAvailableParameterOverridesResult struct {
	AvailableParameterOverrides []PostgresAvailableParameterOverride `json:"availableParameterOverrides"`
}

// PostgresExport defines model for postgresExport.
type PostgresExport struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        string    `json:"id"`

	// Url URL to download the Postgres export
	Url *string `json:"url,omitempty"`
}

// PostgresPlans defines model for postgresPlans.
type PostgresPlans string

// PostgresProcess A single live process from pg_stat_activity.
type PostgresProcess struct {
	ApplicationName *string    `json:"applicationName,omitempty"`
	BackendStart    *time.Time `json:"backendStart,omitempty"`
	ClientAddr      *string    `json:"clientAddr,omitempty"`
	DatabaseName    *string    `json:"databaseName,omitempty"`

	// Duration Duration of the query, in seconds.
	Duration *float32 `json:"duration,omitempty"`

	// IsLeader Whether this process is running against the primary instance of a highly available database.
	IsLeader      *bool      `json:"isLeader,omitempty"`
	Pid           *int       `json:"pid,omitempty"`
	Query         *string    `json:"query,omitempty"`
	QueryStart    *time.Time `json:"queryStart,omitempty"`
	State         *string    `json:"state,omitempty"`
	Username      *string    `json:"username,omitempty"`
	WaitEvent     *string    `json:"waitEvent,omitempty"`
	WaitEventType *string    `json:"waitEventType,omitempty"`
}

// PostgresProcessesResult defines model for postgresProcessesResult.
type PostgresProcessesResult struct {
	Processes []PostgresProcess `json:"processes"`
}

// PostgresQueryStatistic A single query from pg_stat_statements.
type PostgresQueryStatistic struct {
	Calls               *int     `json:"calls,omitempty"`
	LocalBlocksDirtied  *int     `json:"localBlocksDirtied,omitempty"`
	LocalBlocksHit      *int     `json:"localBlocksHit,omitempty"`
	LocalBlocksRead     *int     `json:"localBlocksRead,omitempty"`
	LocalBlocksWritten  *int     `json:"localBlocksWritten,omitempty"`
	MaxTimeMs           *float32 `json:"maxTimeMs,omitempty"`
	MeanTimeMs          *float32 `json:"meanTimeMs,omitempty"`
	MinTimeMs           *float32 `json:"minTimeMs,omitempty"`
	Query               *string  `json:"query,omitempty"`
	QueryId             *string  `json:"queryId,omitempty"`
	Rows                *int     `json:"rows,omitempty"`
	SharedBlocksDirtied *int     `json:"sharedBlocksDirtied,omitempty"`
	SharedBlocksHit     *int     `json:"sharedBlocksHit,omitempty"`
	SharedBlocksRead    *int     `json:"sharedBlocksRead,omitempty"`
	SharedBlocksWritten *int     `json:"sharedBlocksWritten,omitempty"`
	StddevTimeMs        *float32 `json:"stddevTimeMs,omitempty"`
	TempBlocksRead      *int     `json:"tempBlocksRead,omitempty"`
	TempBlocksWritten   *int     `json:"tempBlocksWritten,omitempty"`
	TotalTimeMs         *float32 `json:"totalTimeMs,omitempty"`
}

// PostgresReplicationSetupInput defines model for postgresReplicationSetupInput.
type PostgresReplicationSetupInput struct {
	// AllTablesPublicationName Publication name to create.
	AllTablesPublicationName *string `json:"allTablesPublicationName,omitempty"`

	// DatabaseName Database to replicate.
	DatabaseName string `json:"databaseName"`

	// ReplicationSlotName Replication slot name to create.
	ReplicationSlotName *string `json:"replicationSlotName,omitempty"`

	// RestartNow Immediately enqueue a restart to apply.
	RestartNow *bool `json:"restartNow,omitempty"`

	// SchemaName Schema to replicate.
	SchemaName string `json:"schemaName"`
}

// PostgresSize The size of an index, table, or database.
type PostgresSize struct {
	Bytes    *int    `json:"Bytes,omitempty"`
	Database *string `json:"Database,omitempty"`
	Index    *string `json:"Index,omitempty"`
	Schema   *string `json:"Schema,omitempty"`
	Table    *string `json:"Table,omitempty"`
}

// PostgresSizesResult defines model for postgresSizesResult.
type PostgresSizesResult struct {
	Sizes []PostgresSize `json:"sizes"`
}

// PostgresTableScan The number of sequential scans performed against a table.
type PostgresTableScan struct {
	Database *string `json:"Database,omitempty"`
	Scans    *int    `json:"Scans,omitempty"`
	Schema   *string `json:"Schema,omitempty"`
	Table    *string `json:"Table,omitempty"`
}

// PostgresTableScansResult defines model for postgresTableScansResult.
type PostgresTableScansResult struct {
	TableScans []PostgresTableScan `json:"tableScans"`
}

// PostgresTopQueriesResult defines model for postgresTopQueriesResult.
type PostgresTopQueriesResult struct {
	TopQueries []PostgresQueryStatistic `json:"topQueries"`
}

// RecoveryInfo defines model for recoveryInfo.
type RecoveryInfo struct {
	// RecoveryStatus Availability of point-in-time recovery.
	RecoveryStatus RecoveryInfoRecoveryStatus `json:"recoveryStatus"`
	StartsAt       *time.Time                 `json:"startsAt,omitempty"`
}

// RecoveryInfoRecoveryStatus Availability of point-in-time recovery.
type RecoveryInfoRecoveryStatus string

// RecoveryInput defines model for recoveryInput.
type RecoveryInput struct {
	// DatadogApiKey Datadog API key to use for monitoring the new database. Defaults to the API key of the original database. Use an empty string to prevent copying of the API key to the new database.
	DatadogApiKey *string `json:"datadogApiKey,omitempty"`

	// DatadogSite Datadog region code to use for monitoring the new database. Defaults to the region code of the original database. Use an empty string to prevent copying of the region code to the new database.
	DatadogSite *string `json:"datadogSite,omitempty"`

	// EnvironmentId The environment to create the new database in. Defaults to the environment of the original database.
	EnvironmentId *string `json:"environmentId,omitempty"`

	// Plan The plan to use for the new database. Defaults to the same plan as the original database. Cannot be a lower tier plan than the original database.
	Plan *string `json:"plan,omitempty"`

	// RestoreName Name of the new database.
	RestoreName *string `json:"restoreName,omitempty"`

	// RestoreTime The point in time to restore the database to. See `/recovery-info` for restore availability
	RestoreTime time.Time `json:"restoreTime"`
}
