// Package artifactsources provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package artifactsources

import (
	"time"
)

// Defines values for ArtifactSourceGitRegion.
const (
	ArtifactSourceGitRegionFrankfurt ArtifactSourceGitRegion = "frankfurt"
	ArtifactSourceGitRegionOhio      ArtifactSourceGitRegion = "ohio"
	ArtifactSourceGitRegionOregon    ArtifactSourceGitRegion = "oregon"
	ArtifactSourceGitRegionSingapore ArtifactSourceGitRegion = "singapore"
	ArtifactSourceGitRegionVirginia  ArtifactSourceGitRegion = "virginia"
)

// Defines values for ArtifactSourcePATCHGitRegion.
const (
	ArtifactSourcePATCHGitRegionFrankfurt ArtifactSourcePATCHGitRegion = "frankfurt"
	ArtifactSourcePATCHGitRegionOhio      ArtifactSourcePATCHGitRegion = "ohio"
	ArtifactSourcePATCHGitRegionOregon    ArtifactSourcePATCHGitRegion = "oregon"
	ArtifactSourcePATCHGitRegionSingapore ArtifactSourcePATCHGitRegion = "singapore"
	ArtifactSourcePATCHGitRegionVirginia  ArtifactSourcePATCHGitRegion = "virginia"
)

// ArtifactSource defines model for artifactSource.
type ArtifactSource struct {
	CreatedAt time.Time `json:"createdAt"`

	// Git Present when the artifact source is currently build-based. Mutually exclusive with `image`.
	Git *ArtifactSourceGit `json:"git,omitempty"`
	Id  ArtifactSourceId   `json:"id"`

	// Image Present when the artifact source is currently image-based. Mutually exclusive with `git`.
	Image *ArtifactSourceImage `json:"image,omitempty"`
	Name  string               `json:"name"`

	// OwnerId ID of the workspace this artifact source belongs to.
	OwnerId string `json:"ownerId"`

	// ProjectId ID of the project this artifact source is scoped to, if any.
	ProjectId *string   `json:"projectId,omitempty"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// ArtifactSourceGit defines model for artifactSourceGit.
type ArtifactSourceGit struct {
	BaseDir        *string `json:"baseDir,omitempty"`
	Branch         *string `json:"branch,omitempty"`
	BuildCommand   *string `json:"buildCommand,omitempty"`
	DockerfilePath *string `json:"dockerfilePath,omitempty"`
	EnvId          string  `json:"envId"`

	// Region Defaults to "oregon"
	Region               *ArtifactSourceGitRegion `json:"region,omitempty"`
	RegistryCredentialId *string                  `json:"registryCredentialId,omitempty"`
	RepoUrl              *string                  `json:"repoUrl,omitempty"`
	RootDir              *string                  `json:"rootDir,omitempty"`
}

// ArtifactSourceGitRegion Defaults to "oregon"
type ArtifactSourceGitRegion string

// ArtifactSourceId defines model for artifactSourceId.
type ArtifactSourceId = string

// ArtifactSourceImage defines model for artifactSourceImage.
type ArtifactSourceImage struct {
	ImageUrl             string  `json:"imageUrl"`
	OwnerId              string  `json:"ownerId"`
	RegistryCredentialId *string `json:"registryCredentialId,omitempty"`
}

// ArtifactSourcePATCHGit defines model for artifactSourcePATCHGit.
type ArtifactSourcePATCHGit struct {
	BaseDir        *string `json:"baseDir,omitempty"`
	Branch         *string `json:"branch,omitempty"`
	BuildCommand   *string `json:"buildCommand,omitempty"`
	DockerfilePath *string `json:"dockerfilePath,omitempty"`
	EnvId          *string `json:"envId,omitempty"`

	// Region Region for the build. Honored only when this PATCH performs an image→build transition; rejected on a pure build patch (the cluster is pinned for an existing build), and must match the prior build region when switching back to build after time as an external image. Defaults to "oregon" for first-time builds.
	Region               *ArtifactSourcePATCHGitRegion `json:"region,omitempty"`
	RegistryCredentialId *string                       `json:"registryCredentialId,omitempty"`
	RepoUrl              *string                       `json:"repoUrl,omitempty"`
	RootDir              *string                       `json:"rootDir,omitempty"`
}

// ArtifactSourcePATCHGitRegion Region for the build. Honored only when this PATCH performs an image→build transition; rejected on a pure build patch (the cluster is pinned for an existing build), and must match the prior build region when switching back to build after time as an external image. Defaults to "oregon" for first-time builds.
type ArtifactSourcePATCHGitRegion string

// ArtifactSourcePATCHImage Patch shape for an artifact source's image identity. Unset fields are left unchanged on the underlying image reference. ownerId is intentionally omitted — an artifact source's owner is fixed at creation, and changing the image's owner would amount to a different identity.
type ArtifactSourcePATCHImage struct {
	ImageUrl             *string `json:"imageUrl,omitempty"`
	RegistryCredentialId *string `json:"registryCredentialId,omitempty"`
}

// ArtifactSourcePATCHInput defines model for artifactSourcePATCHInput.
type ArtifactSourcePATCHInput struct {
	Git *ArtifactSourcePATCHGit `json:"git,omitempty"`

	// Image Patch shape for an artifact source's image identity. Unset fields are left unchanged on the underlying image reference. ownerId is intentionally omitted — an artifact source's owner is fixed at creation, and changing the image's owner would amount to a different identity.
	Image *ArtifactSourcePATCHImage `json:"image,omitempty"`
	Name  *string                   `json:"name,omitempty"`
}

// ArtifactSourcePOSTInput defines model for artifactSourcePOSTInput.
type ArtifactSourcePOSTInput struct {
	Git       *ArtifactSourceGit   `json:"git,omitempty"`
	Image     *ArtifactSourceImage `json:"image,omitempty"`
	Name      string               `json:"name"`
	OwnerId   string               `json:"ownerId"`
	ProjectId *string              `json:"projectId,omitempty"`
}

// ArtifactSourceWithCursor defines model for artifactSourceWithCursor.
type ArtifactSourceWithCursor struct {
	ArtifactSource ArtifactSource `json:"artifactSource"`
	Cursor         string         `json:"cursor"`
}

// ArtifactSourceIdParam defines model for artifactSourceIdParam.
type ArtifactSourceIdParam = ArtifactSourceId
