// Package artifactsources provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package artifactsources

import (
	"time"
)

// Defines values for ArtifactSourceGitRegion.
const (
	ArtifactSourceGitRegionFrankfurt ArtifactSourceGitRegion = "frankfurt"
	ArtifactSourceGitRegionOhio      ArtifactSourceGitRegion = "ohio"
	ArtifactSourceGitRegionOregon    ArtifactSourceGitRegion = "oregon"
	ArtifactSourceGitRegionSingapore ArtifactSourceGitRegion = "singapore"
	ArtifactSourceGitRegionVirginia  ArtifactSourceGitRegion = "virginia"
)

// Valid indicates whether the value is a known member of the ArtifactSourceGitRegion enum.
func (e ArtifactSourceGitRegion) Valid() bool {
	switch e {
	case ArtifactSourceGitRegionFrankfurt:
		return true
	case ArtifactSourceGitRegionOhio:
		return true
	case ArtifactSourceGitRegionOregon:
		return true
	case ArtifactSourceGitRegionSingapore:
		return true
	case ArtifactSourceGitRegionVirginia:
		return true
	default:
		return false
	}
}

// Defines values for ArtifactSourceGitRuntime.
const (
	ArtifactSourceGitRuntimeDocker ArtifactSourceGitRuntime = "docker"
	ArtifactSourceGitRuntimeElixir ArtifactSourceGitRuntime = "elixir"
	ArtifactSourceGitRuntimeGo     ArtifactSourceGitRuntime = "go"
	ArtifactSourceGitRuntimeNode   ArtifactSourceGitRuntime = "node"
	ArtifactSourceGitRuntimePython ArtifactSourceGitRuntime = "python"
	ArtifactSourceGitRuntimeRuby   ArtifactSourceGitRuntime = "ruby"
	ArtifactSourceGitRuntimeRust   ArtifactSourceGitRuntime = "rust"
)

// Valid indicates whether the value is a known member of the ArtifactSourceGitRuntime enum.
func (e ArtifactSourceGitRuntime) Valid() bool {
	switch e {
	case ArtifactSourceGitRuntimeDocker:
		return true
	case ArtifactSourceGitRuntimeElixir:
		return true
	case ArtifactSourceGitRuntimeGo:
		return true
	case ArtifactSourceGitRuntimeNode:
		return true
	case ArtifactSourceGitRuntimePython:
		return true
	case ArtifactSourceGitRuntimeRuby:
		return true
	case ArtifactSourceGitRuntimeRust:
		return true
	default:
		return false
	}
}

// Defines values for ArtifactSourcePATCHGitRegion.
const (
	ArtifactSourcePATCHGitRegionFrankfurt ArtifactSourcePATCHGitRegion = "frankfurt"
	ArtifactSourcePATCHGitRegionOhio      ArtifactSourcePATCHGitRegion = "ohio"
	ArtifactSourcePATCHGitRegionOregon    ArtifactSourcePATCHGitRegion = "oregon"
	ArtifactSourcePATCHGitRegionSingapore ArtifactSourcePATCHGitRegion = "singapore"
	ArtifactSourcePATCHGitRegionVirginia  ArtifactSourcePATCHGitRegion = "virginia"
)

// Valid indicates whether the value is a known member of the ArtifactSourcePATCHGitRegion enum.
func (e ArtifactSourcePATCHGitRegion) Valid() bool {
	switch e {
	case ArtifactSourcePATCHGitRegionFrankfurt:
		return true
	case ArtifactSourcePATCHGitRegionOhio:
		return true
	case ArtifactSourcePATCHGitRegionOregon:
		return true
	case ArtifactSourcePATCHGitRegionSingapore:
		return true
	case ArtifactSourcePATCHGitRegionVirginia:
		return true
	default:
		return false
	}
}

// Defines values for ArtifactSourcePATCHGitRuntime.
const (
	ArtifactSourcePATCHGitRuntimeDocker ArtifactSourcePATCHGitRuntime = "docker"
	ArtifactSourcePATCHGitRuntimeElixir ArtifactSourcePATCHGitRuntime = "elixir"
	ArtifactSourcePATCHGitRuntimeGo     ArtifactSourcePATCHGitRuntime = "go"
	ArtifactSourcePATCHGitRuntimeNode   ArtifactSourcePATCHGitRuntime = "node"
	ArtifactSourcePATCHGitRuntimePython ArtifactSourcePATCHGitRuntime = "python"
	ArtifactSourcePATCHGitRuntimeRuby   ArtifactSourcePATCHGitRuntime = "ruby"
	ArtifactSourcePATCHGitRuntimeRust   ArtifactSourcePATCHGitRuntime = "rust"
)

// Valid indicates whether the value is a known member of the ArtifactSourcePATCHGitRuntime enum.
func (e ArtifactSourcePATCHGitRuntime) Valid() bool {
	switch e {
	case ArtifactSourcePATCHGitRuntimeDocker:
		return true
	case ArtifactSourcePATCHGitRuntimeElixir:
		return true
	case ArtifactSourcePATCHGitRuntimeGo:
		return true
	case ArtifactSourcePATCHGitRuntimeNode:
		return true
	case ArtifactSourcePATCHGitRuntimePython:
		return true
	case ArtifactSourcePATCHGitRuntimeRuby:
		return true
	case ArtifactSourcePATCHGitRuntimeRust:
		return true
	default:
		return false
	}
}

// Defines values for BuildRuntime.
const (
	Docker BuildRuntime = "docker"
	Elixir BuildRuntime = "elixir"
	Go     BuildRuntime = "go"
	Node   BuildRuntime = "node"
	Python BuildRuntime = "python"
	Ruby   BuildRuntime = "ruby"
	Rust   BuildRuntime = "rust"
)

// Valid indicates whether the value is a known member of the BuildRuntime enum.
func (e BuildRuntime) Valid() bool {
	switch e {
	case Docker:
		return true
	case Elixir:
		return true
	case Go:
		return true
	case Node:
		return true
	case Python:
		return true
	case Ruby:
		return true
	case Rust:
		return true
	default:
		return false
	}
}

// Defines values for BuildStatus.
const (
	Canceled   BuildStatus = "canceled"
	Created    BuildStatus = "created"
	Failed     BuildStatus = "failed"
	InProgress BuildStatus = "inProgress"
	Succeeded  BuildStatus = "succeeded"
	Unknown    BuildStatus = "unknown"
)

// Valid indicates whether the value is a known member of the BuildStatus enum.
func (e BuildStatus) Valid() bool {
	switch e {
	case Canceled:
		return true
	case Created:
		return true
	case Failed:
		return true
	case InProgress:
		return true
	case Succeeded:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Artifact defines model for artifact.
type Artifact struct {
	ArtifactSourceId ArtifactSourceId `json:"artifactSourceId"`

	// Build Present when the artifact source is currently build-based. Mutually exclusive with `image`.
	Build     *Build     `json:"build,omitempty"`
	CreatedAt time.Time  `json:"createdAt"`
	Id        ArtifactId `json:"id"`

	// Image Present when the artifact source is currently image-based. Mutually exclusive with `build`.
	Image     *Image    `json:"image,omitempty"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// ArtifactId defines model for artifactId.
type ArtifactId = string

// ArtifactSource defines model for artifactSource.
type ArtifactSource struct {
	CreatedAt time.Time `json:"createdAt"`

	// Git Present when the artifact source is currently build-based. Mutually exclusive with `image`.
	Git *ArtifactSourceGit `json:"git,omitempty"`
	Id  ArtifactSourceId   `json:"id"`

	// Image Present when the artifact source is currently image-based. Mutually exclusive with `git`.
	Image *ArtifactSourceImage `json:"image,omitempty"`
	Name  string               `json:"name"`

	// OwnerId ID of the workspace this artifact source belongs to.
	OwnerId string `json:"ownerId"`

	// ProjectId ID of the project this artifact source is scoped to, if any.
	ProjectId *string   `json:"projectId,omitempty"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// ArtifactSourceGit defines model for artifactSourceGit.
type ArtifactSourceGit struct {
	BaseDir      *string `json:"baseDir,omitempty"`
	Branch       *string `json:"branch,omitempty"`
	BuildCommand *string `json:"buildCommand,omitempty"`

	// BuildFilter Glob patterns matched against files changed by a commit. When set, a commit only triggers a build when at least one changed file matches `paths` and none match `ignoredPaths`. Useful for monorepos where a single repo backs many services.
	BuildFilter    *BuildFilter `json:"buildFilter,omitempty"`
	DockerfilePath *string      `json:"dockerfilePath,omitempty"`

	// Region Defaults to "oregon"
	Region               *ArtifactSourceGitRegion `json:"region,omitempty"`
	RegistryCredentialId *string                  `json:"registryCredentialId,omitempty"`
	RepoUrl              *string                  `json:"repoUrl,omitempty"`
	RootDir              *string                  `json:"rootDir,omitempty"`

	// Runtime Build runtime for the artifact source. Static sites are not supported for artifact sources.
	Runtime ArtifactSourceGitRuntime `json:"runtime"`
}

// ArtifactSourceGitRegion Defaults to "oregon"
type ArtifactSourceGitRegion string

// ArtifactSourceGitRuntime Build runtime for the artifact source. Static sites are not supported for artifact sources.
type ArtifactSourceGitRuntime string

// ArtifactSourceId defines model for artifactSourceId.
type ArtifactSourceId = string

// ArtifactSourceImage defines model for artifactSourceImage.
type ArtifactSourceImage struct {
	ImageUrl             string  `json:"imageUrl"`
	OwnerId              string  `json:"ownerId"`
	RegistryCredentialId *string `json:"registryCredentialId,omitempty"`
}

// ArtifactSourcePATCHGit defines model for artifactSourcePATCHGit.
type ArtifactSourcePATCHGit struct {
	BaseDir      *string `json:"baseDir,omitempty"`
	Branch       *string `json:"branch,omitempty"`
	BuildCommand *string `json:"buildCommand,omitempty"`

	// BuildFilter Glob patterns matched against files changed by a commit. When set, a commit only triggers a build when at least one changed file matches `paths` and none match `ignoredPaths`. Useful for monorepos where a single repo backs many services.
	BuildFilter    *BuildFilter `json:"buildFilter,omitempty"`
	DockerfilePath *string      `json:"dockerfilePath,omitempty"`

	// Region Region for the build. Honored only when this PATCH performs an image→build transition; rejected on a pure build patch (the cluster is pinned for an existing build), and must match the prior build region when switching back to build after time as an external image. Defaults to "oregon" for first-time builds.
	Region               *ArtifactSourcePATCHGitRegion `json:"region,omitempty"`
	RegistryCredentialId *string                       `json:"registryCredentialId,omitempty"`
	RepoUrl              *string                       `json:"repoUrl,omitempty"`
	RootDir              *string                       `json:"rootDir,omitempty"`

	// Runtime Build runtime for the artifact source. Static sites are not supported for artifact sources.
	Runtime *ArtifactSourcePATCHGitRuntime `json:"runtime,omitempty"`
}

// ArtifactSourcePATCHGitRegion Region for the build. Honored only when this PATCH performs an image→build transition; rejected on a pure build patch (the cluster is pinned for an existing build), and must match the prior build region when switching back to build after time as an external image. Defaults to "oregon" for first-time builds.
type ArtifactSourcePATCHGitRegion string

// ArtifactSourcePATCHGitRuntime Build runtime for the artifact source. Static sites are not supported for artifact sources.
type ArtifactSourcePATCHGitRuntime string

// ArtifactSourcePATCHImage Patch shape for an artifact source's image identity. Unset fields are left unchanged on the underlying image reference. ownerId is intentionally omitted — an artifact source's owner is fixed at creation, and changing the image's owner would amount to a different identity.
type ArtifactSourcePATCHImage struct {
	ImageUrl             *string `json:"imageUrl,omitempty"`
	RegistryCredentialId *string `json:"registryCredentialId,omitempty"`
}

// ArtifactSourcePATCHInput defines model for artifactSourcePATCHInput.
type ArtifactSourcePATCHInput struct {
	Git *ArtifactSourcePATCHGit `json:"git,omitempty"`

	// Image Patch shape for an artifact source's image identity. Unset fields are left unchanged on the underlying image reference. ownerId is intentionally omitted — an artifact source's owner is fixed at creation, and changing the image's owner would amount to a different identity.
	Image *ArtifactSourcePATCHImage `json:"image,omitempty"`
	Name  *string                   `json:"name,omitempty"`
}

// ArtifactSourcePOSTInput defines model for artifactSourcePOSTInput.
type ArtifactSourcePOSTInput struct {
	Git       *ArtifactSourceGit   `json:"git,omitempty"`
	Image     *ArtifactSourceImage `json:"image,omitempty"`
	Name      string               `json:"name"`
	OwnerId   string               `json:"ownerId"`
	ProjectId *string              `json:"projectId,omitempty"`
}

// ArtifactSourceWithCursor defines model for artifactSourceWithCursor.
type ArtifactSourceWithCursor struct {
	ArtifactSource ArtifactSource `json:"artifactSource"`
	Cursor         string         `json:"cursor"`
}

// Build Present when the artifact source is currently build-based. Mutually exclusive with `image`.
type Build struct {
	BuildFinishedAt *time.Time    `json:"buildFinishedAt,omitempty"`
	BuildStartedAt  *time.Time    `json:"buildStartedAt,omitempty"`
	CommitId        *string       `json:"commitId,omitempty"`
	CommitUrl       *string       `json:"commitUrl,omitempty"`
	Id              string        `json:"id"`
	Runtime         *BuildRuntime `json:"runtime,omitempty"`
	Status          *BuildStatus  `json:"status,omitempty"`
}

// BuildRuntime defines model for Build.Runtime.
type BuildRuntime string

// BuildStatus defines model for Build.Status.
type BuildStatus string

// BuildFilter Glob patterns matched against files changed by a commit. When set, a commit only triggers a build when at least one changed file matches `paths` and none match `ignoredPaths`. Useful for monorepos where a single repo backs many services.
type BuildFilter struct {
	IgnoredPaths []string `json:"ignoredPaths"`
	Paths        []string `json:"paths"`
}

// Image Present when the artifact source is currently image-based. Mutually exclusive with `build`.
type Image struct {
	SHA                  *string `json:"SHA,omitempty"`
	ImageUrl             *string `json:"imageUrl,omitempty"`
	ImageVersionId       *string `json:"imageVersionId,omitempty"`
	Ref                  *string `json:"ref,omitempty"`
	RegistryCredentialId *string `json:"registryCredentialId,omitempty"`
}

// ArtifactSourceIdParam defines model for artifactSourceIdParam.
type ArtifactSourceIdParam = ArtifactSourceId
