// Package logs provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package logs

import (
	"time"
)

// Defines values for LogDirection.
const (
	Backward LogDirection = "backward"
	Forward  LogDirection = "forward"
)

// Defines values for LogLabelName.
const (
	LogLabelNameHost       LogLabelName = "host"
	LogLabelNameInstance   LogLabelName = "instance"
	LogLabelNameLevel      LogLabelName = "level"
	LogLabelNameMethod     LogLabelName = "method"
	LogLabelNamePath       LogLabelName = "path"
	LogLabelNameResource   LogLabelName = "resource"
	LogLabelNameStatusCode LogLabelName = "statusCode"
	LogLabelNameText       LogLabelName = "text"
	LogLabelNameType       LogLabelName = "type"
)

// Defines values for LogLabelParam.
const (
	LogLabelParamHost       LogLabelParam = "host"
	LogLabelParamInstance   LogLabelParam = "instance"
	LogLabelParamLevel      LogLabelParam = "level"
	LogLabelParamMethod     LogLabelParam = "method"
	LogLabelParamStatusCode LogLabelParam = "statusCode"
	LogLabelParamType       LogLabelParam = "type"
)

// Log A log entry with metadata
type Log struct {
	// Id A unique ID of the log entry
	Id     string     `json:"id"`
	Labels []LogLabel `json:"labels"`

	// Message The message of the log entry
	Message string `json:"message"`

	// Timestamp The timestamp of the log entry
	Timestamp time.Time `json:"timestamp"`
}

// LogDirection defines model for logDirection.
type LogDirection string

// LogLabel A log label
type LogLabel struct {
	Name LogLabelName `json:"name"`

	// Value The value of the log label
	Value string `json:"value"`
}

// LogLabelName defines model for logLabelName.
type LogLabelName string

// LogDirectionParam defines model for logDirectionParam.
type LogDirectionParam = LogDirection

// LogFilterHost defines model for logFilterHost.
type LogFilterHost = []string

// LogFilterInstance defines model for logFilterInstance.
type LogFilterInstance = []string

// LogFilterLevel defines model for logFilterLevel.
type LogFilterLevel = []string

// LogFilterMethod defines model for logFilterMethod.
type LogFilterMethod = []string

// LogFilterPath defines model for logFilterPath.
type LogFilterPath = []string

// LogFilterResource defines model for logFilterResource.
type LogFilterResource = []string

// LogFilterStatusCode defines model for logFilterStatusCode.
type LogFilterStatusCode = []string

// LogFilterText defines model for logFilterText.
type LogFilterText = []string

// LogFilterType defines model for logFilterType.
type LogFilterType = []string

// LogLabelParam defines model for logLabelParam.
type LogLabelParam string
