// Package logs provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package logs

import (
	"time"
)

// Defines values for LogDirection.
const (
	Backward LogDirection = "backward"
	Forward  LogDirection = "forward"
)

// Valid indicates whether the value is a known member of the LogDirection enum.
func (e LogDirection) Valid() bool {
	switch e {
	case Backward:
		return true
	case Forward:
		return true
	default:
		return false
	}
}

// Defines values for LogLabelName.
const (
	LogLabelNameBlocked          LogLabelName = "blocked"
	LogLabelNameHost             LogLabelName = "host"
	LogLabelNameInstance         LogLabelName = "instance"
	LogLabelNameLevel            LogLabelName = "level"
	LogLabelNameMethod           LogLabelName = "method"
	LogLabelNamePath             LogLabelName = "path"
	LogLabelNameResource         LogLabelName = "resource"
	LogLabelNameStatusCode       LogLabelName = "statusCode"
	LogLabelNameTask             LogLabelName = "task"
	LogLabelNameTaskRun          LogLabelName = "taskRun"
	LogLabelNameText             LogLabelName = "text"
	LogLabelNameType             LogLabelName = "type"
	LogLabelNameWorkflowService  LogLabelName = "workflowService"
	LogLabelNameWorkflowVeresion LogLabelName = "workflowVeresion"
)

// Valid indicates whether the value is a known member of the LogLabelName enum.
func (e LogLabelName) Valid() bool {
	switch e {
	case LogLabelNameBlocked:
		return true
	case LogLabelNameHost:
		return true
	case LogLabelNameInstance:
		return true
	case LogLabelNameLevel:
		return true
	case LogLabelNameMethod:
		return true
	case LogLabelNamePath:
		return true
	case LogLabelNameResource:
		return true
	case LogLabelNameStatusCode:
		return true
	case LogLabelNameTask:
		return true
	case LogLabelNameTaskRun:
		return true
	case LogLabelNameText:
		return true
	case LogLabelNameType:
		return true
	case LogLabelNameWorkflowService:
		return true
	case LogLabelNameWorkflowVeresion:
		return true
	default:
		return false
	}
}

// Defines values for LogStreamPreviewSetting.
const (
	LogStreamPreviewSettingDrop LogStreamPreviewSetting = "drop"
	LogStreamPreviewSettingSend LogStreamPreviewSetting = "send"
)

// Valid indicates whether the value is a known member of the LogStreamPreviewSetting enum.
func (e LogStreamPreviewSetting) Valid() bool {
	switch e {
	case LogStreamPreviewSettingDrop:
		return true
	case LogStreamPreviewSettingSend:
		return true
	default:
		return false
	}
}

// Defines values for LogStreamSetting.
const (
	LogStreamSettingDrop LogStreamSetting = "drop"
	LogStreamSettingSend LogStreamSetting = "send"
)

// Valid indicates whether the value is a known member of the LogStreamSetting enum.
func (e LogStreamSetting) Valid() bool {
	switch e {
	case LogStreamSettingDrop:
		return true
	case LogStreamSettingSend:
		return true
	default:
		return false
	}
}

// Defines values for LogLabelParam.
const (
	LogLabelParamHost       LogLabelParam = "host"
	LogLabelParamInstance   LogLabelParam = "instance"
	LogLabelParamLevel      LogLabelParam = "level"
	LogLabelParamMethod     LogLabelParam = "method"
	LogLabelParamStatusCode LogLabelParam = "statusCode"
	LogLabelParamType       LogLabelParam = "type"
)

// Valid indicates whether the value is a known member of the LogLabelParam enum.
func (e LogLabelParam) Valid() bool {
	switch e {
	case LogLabelParamHost:
		return true
	case LogLabelParamInstance:
		return true
	case LogLabelParamLevel:
		return true
	case LogLabelParamMethod:
		return true
	case LogLabelParamStatusCode:
		return true
	case LogLabelParamType:
		return true
	default:
		return false
	}
}

// Log A log entry with metadata
type Log struct {
	// Id A unique ID of the log entry
	Id     string     `json:"id"`
	Labels []LogLabel `json:"labels"`

	// Message The message of the log entry
	Message string `json:"message"`

	// Timestamp The timestamp of the log entry
	Timestamp time.Time `json:"timestamp"`
}

// LogDirection defines model for logDirection.
type LogDirection string

// LogLabel A log label
type LogLabel struct {
	Name LogLabelName `json:"name"`

	// Value The value of the log label
	Value string `json:"value"`
}

// LogLabelName defines model for logLabelName.
type LogLabelName string

// LogStreamEndpoint The endpoint to stream logs to.
type LogStreamEndpoint = string

// LogStreamOwnerUpdate defines model for logStreamOwnerUpdate.
type LogStreamOwnerUpdate struct {
	// Endpoint The endpoint to stream logs to.
	Endpoint *LogStreamEndpoint `json:"endpoint,omitempty"`

	// Preview Whether to send logs or drop them.
	Preview LogStreamPreviewSetting `json:"preview"`

	// Token The optional token to authenticate the log stream.
	Token *LogStreamToken `json:"token,omitempty"`
}

// LogStreamPreviewSetting Whether to send logs or drop them.
type LogStreamPreviewSetting string

// LogStreamResourceUpdate defines model for logStreamResourceUpdate.
type LogStreamResourceUpdate struct {
	// Endpoint The endpoint to stream logs to.
	Endpoint *LogStreamEndpoint `json:"endpoint,omitempty"`

	// Setting Whether to send logs or drop them.
	Setting LogStreamSetting `json:"setting"`

	// Token The optional token to authenticate the log stream.
	Token *LogStreamToken `json:"token,omitempty"`
}

// LogStreamSetting Whether to send logs or drop them.
type LogStreamSetting string

// LogStreamToken The optional token to authenticate the log stream.
type LogStreamToken = string

// OwnerLogStreamSetting Owner log stream settings
type OwnerLogStreamSetting struct {
	// Endpoint The endpoint to stream logs to.
	Endpoint *string `json:"endpoint,omitempty"`

	// OwnerId The ID of the owner.
	OwnerId *string `json:"ownerId,omitempty"`

	// Preview Whether to send logs or drop them.
	Preview *LogStreamPreviewSetting `json:"preview,omitempty"`
}

// ResourceLogStreamSetting Resource log stream overrides
type ResourceLogStreamSetting struct {
	// Endpoint The endpoint to stream logs to. Must be present if setting is send. Cannot be present if setting is drop.
	Endpoint *string `json:"endpoint,omitempty"`

	// ResourceId The ID of the resource.
	ResourceId *string `json:"resourceId,omitempty"`

	// Setting Whether to send logs or drop them.
	Setting *LogStreamSetting `json:"setting,omitempty"`
}

// DirectionParam defines model for directionParam.
type DirectionParam = LogDirection

// LogFilterHost defines model for logFilterHost.
type LogFilterHost = []string

// LogFilterInstance defines model for logFilterInstance.
type LogFilterInstance = []string

// LogFilterLevel defines model for logFilterLevel.
type LogFilterLevel = []string

// LogFilterMethod defines model for logFilterMethod.
type LogFilterMethod = []string

// LogFilterPath defines model for logFilterPath.
type LogFilterPath = []string

// LogFilterResource defines model for logFilterResource.
type LogFilterResource = []string

// LogFilterStatusCode defines model for logFilterStatusCode.
type LogFilterStatusCode = []string

// LogFilterTask defines model for logFilterTask.
type LogFilterTask = []string

// LogFilterTaskRun defines model for logFilterTaskRun.
type LogFilterTaskRun = []string

// LogFilterText defines model for logFilterText.
type LogFilterText = []string

// LogFilterType defines model for logFilterType.
type LogFilterType = []string

// LogLabelParam defines model for logLabelParam.
type LogLabelParam string

// LogStreamIdFilter defines model for logStreamIdFilter.
type LogStreamIdFilter = []string

// LogStreamSettingFilter defines model for logStreamSettingFilter.
type LogStreamSettingFilter = []LogStreamSetting

// GetOwnerLogsStreams200Response Owner log stream settings
type GetOwnerLogsStreams200Response = OwnerLogStreamSetting

// GetResourceLogsStreams200Response Resource log stream overrides
type GetResourceLogsStreams200Response = ResourceLogStreamSetting

// ResourceLogsStreams200Response defines model for ResourceLogsStreams200Response.
type ResourceLogsStreams200Response = []ResourceLogStreamSetting
