// Package eventtypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package eventtypes

// Defines values for EventType.
const (
	EventTypeAutoDeployDisabled                    EventType = "auto_deploy_disabled"
	EventTypeAutoDeployEnabled                     EventType = "auto_deploy_enabled"
	EventTypeAutoscalingConfigChanged              EventType = "autoscaling_config_changed"
	EventTypeAutoscalingEnded                      EventType = "autoscaling_ended"
	EventTypeAutoscalingStarted                    EventType = "autoscaling_started"
	EventTypeBranchDeleted                         EventType = "branch_deleted"
	EventTypeBuildEnded                            EventType = "build_ended"
	EventTypeBuildStarted                          EventType = "build_started"
	EventTypeCommitIgnored                         EventType = "commit_ignored"
	EventTypeCronJobRunEnded                       EventType = "cron_job_run_ended"
	EventTypeCronJobRunStarted                     EventType = "cron_job_run_started"
	EventTypeDeployEnded                           EventType = "deploy_ended"
	EventTypeDeployStarted                         EventType = "deploy_started"
	EventTypeDiskCreated                           EventType = "disk_created"
	EventTypeDiskDeleted                           EventType = "disk_deleted"
	EventTypeDiskUpdated                           EventType = "disk_updated"
	EventTypeEdgeCacheDisabled                     EventType = "edge_cache_disabled"
	EventTypeEdgeCacheEnabled                      EventType = "edge_cache_enabled"
	EventTypeEdgeCachePurged                       EventType = "edge_cache_purged"
	EventTypeImagePullFailed                       EventType = "image_pull_failed"
	EventTypeInstanceCountChanged                  EventType = "instance_count_changed"
	EventTypeJobRunEnded                           EventType = "job_run_ended"
	EventTypeKeyValueAvailable                     EventType = "key_value_available"
	EventTypeKeyValueConfigRestart                 EventType = "key_value_config_restart"
	EventTypeKeyValueUnhealthy                     EventType = "key_value_unhealthy"
	EventTypeMaintenanceEnded                      EventType = "maintenance_ended"
	EventTypeMaintenanceModeEnabled                EventType = "maintenance_mode_enabled"
	EventTypeMaintenanceModeUriUpdated             EventType = "maintenance_mode_uri_updated"
	EventTypeMaintenanceStarted                    EventType = "maintenance_started"
	EventTypePipelineMinutesExhausted              EventType = "pipeline_minutes_exhausted"
	EventTypePlanChanged                           EventType = "plan_changed"
	EventTypePostgresAvailable                     EventType = "postgres_available"
	EventTypePostgresBackupCompleted               EventType = "postgres_backup_completed"
	EventTypePostgresBackupFailed                  EventType = "postgres_backup_failed"
	EventTypePostgresBackupStarted                 EventType = "postgres_backup_started"
	EventTypePostgresClusterLeaderChanged          EventType = "postgres_cluster_leader_changed"
	EventTypePostgresConnectionPoolChanged         EventType = "postgres_connection_pool_changed"
	EventTypePostgresConnectionPoolEnabledChanged  EventType = "postgres_connection_pool_enabled_changed"
	EventTypePostgresCreated                       EventType = "postgres_created"
	EventTypePostgresDiskAutoscalingEnabledChanged EventType = "postgres_disk_autoscaling_enabled_changed"
	EventTypePostgresDiskSizeChanged               EventType = "postgres_disk_size_changed"
	EventTypePostgresHaStatusChanged               EventType = "postgres_ha_status_changed"
	EventTypePostgresPitrCheckpointCompleted       EventType = "postgres_pitr_checkpoint_completed"
	EventTypePostgresPitrCheckpointFailed          EventType = "postgres_pitr_checkpoint_failed"
	EventTypePostgresPitrCheckpointStarted         EventType = "postgres_pitr_checkpoint_started"
	EventTypePostgresReadReplicaStale              EventType = "postgres_read_replica_stale"
	EventTypePostgresReadReplicasChanged           EventType = "postgres_read_replicas_changed"
	EventTypePostgresRestarted                     EventType = "postgres_restarted"
	EventTypePostgresRestoreFailed                 EventType = "postgres_restore_failed"
	EventTypePostgresRestoreSucceeded              EventType = "postgres_restore_succeeded"
	EventTypePostgresUnavailable                   EventType = "postgres_unavailable"
	EventTypePostgresUpgradeFailed                 EventType = "postgres_upgrade_failed"
	EventTypePostgresUpgradeStarted                EventType = "postgres_upgrade_started"
	EventTypePostgresUpgradeSucceeded              EventType = "postgres_upgrade_succeeded"
	EventTypePostgresWalArchiveFailed              EventType = "postgres_wal_archive_failed"
	EventTypePreDeployEnded                        EventType = "pre_deploy_ended"
	EventTypePreDeployStarted                      EventType = "pre_deploy_started"
	EventTypeServerAvailable                       EventType = "server_available"
	EventTypeServerFailed                          EventType = "server_failed"
	EventTypeServerHardwareFailure                 EventType = "server_hardware_failure"
	EventTypeServerRestarted                       EventType = "server_restarted"
	EventTypeServiceResumed                        EventType = "service_resumed"
	EventTypeServiceSuspended                      EventType = "service_suspended"
	EventTypeZeroDowntimeRedeployEnded             EventType = "zero_downtime_redeploy_ended"
	EventTypeZeroDowntimeRedeployStarted           EventType = "zero_downtime_redeploy_started"
)

// Valid indicates whether the value is a known member of the EventType enum.
func (e EventType) Valid() bool {
	switch e {
	case EventTypeAutoDeployDisabled:
		return true
	case EventTypeAutoDeployEnabled:
		return true
	case EventTypeAutoscalingConfigChanged:
		return true
	case EventTypeAutoscalingEnded:
		return true
	case EventTypeAutoscalingStarted:
		return true
	case EventTypeBranchDeleted:
		return true
	case EventTypeBuildEnded:
		return true
	case EventTypeBuildStarted:
		return true
	case EventTypeCommitIgnored:
		return true
	case EventTypeCronJobRunEnded:
		return true
	case EventTypeCronJobRunStarted:
		return true
	case EventTypeDeployEnded:
		return true
	case EventTypeDeployStarted:
		return true
	case EventTypeDiskCreated:
		return true
	case EventTypeDiskDeleted:
		return true
	case EventTypeDiskUpdated:
		return true
	case EventTypeEdgeCacheDisabled:
		return true
	case EventTypeEdgeCacheEnabled:
		return true
	case EventTypeEdgeCachePurged:
		return true
	case EventTypeImagePullFailed:
		return true
	case EventTypeInstanceCountChanged:
		return true
	case EventTypeJobRunEnded:
		return true
	case EventTypeKeyValueAvailable:
		return true
	case EventTypeKeyValueConfigRestart:
		return true
	case EventTypeKeyValueUnhealthy:
		return true
	case EventTypeMaintenanceEnded:
		return true
	case EventTypeMaintenanceModeEnabled:
		return true
	case EventTypeMaintenanceModeUriUpdated:
		return true
	case EventTypeMaintenanceStarted:
		return true
	case EventTypePipelineMinutesExhausted:
		return true
	case EventTypePlanChanged:
		return true
	case EventTypePostgresAvailable:
		return true
	case EventTypePostgresBackupCompleted:
		return true
	case EventTypePostgresBackupFailed:
		return true
	case EventTypePostgresBackupStarted:
		return true
	case EventTypePostgresClusterLeaderChanged:
		return true
	case EventTypePostgresConnectionPoolChanged:
		return true
	case EventTypePostgresConnectionPoolEnabledChanged:
		return true
	case EventTypePostgresCreated:
		return true
	case EventTypePostgresDiskAutoscalingEnabledChanged:
		return true
	case EventTypePostgresDiskSizeChanged:
		return true
	case EventTypePostgresHaStatusChanged:
		return true
	case EventTypePostgresPitrCheckpointCompleted:
		return true
	case EventTypePostgresPitrCheckpointFailed:
		return true
	case EventTypePostgresPitrCheckpointStarted:
		return true
	case EventTypePostgresReadReplicaStale:
		return true
	case EventTypePostgresReadReplicasChanged:
		return true
	case EventTypePostgresRestarted:
		return true
	case EventTypePostgresRestoreFailed:
		return true
	case EventTypePostgresRestoreSucceeded:
		return true
	case EventTypePostgresUnavailable:
		return true
	case EventTypePostgresUpgradeFailed:
		return true
	case EventTypePostgresUpgradeStarted:
		return true
	case EventTypePostgresUpgradeSucceeded:
		return true
	case EventTypePostgresWalArchiveFailed:
		return true
	case EventTypePreDeployEnded:
		return true
	case EventTypePreDeployStarted:
		return true
	case EventTypeServerAvailable:
		return true
	case EventTypeServerFailed:
		return true
	case EventTypeServerHardwareFailure:
		return true
	case EventTypeServerRestarted:
		return true
	case EventTypeServiceResumed:
		return true
	case EventTypeServiceSuspended:
		return true
	case EventTypeZeroDowntimeRedeployEnded:
		return true
	case EventTypeZeroDowntimeRedeployStarted:
		return true
	default:
		return false
	}
}

// Defines values for ServiceEventType.
const (
	ServiceEventTypeAutoDeployDisabled          ServiceEventType = "auto_deploy_disabled"
	ServiceEventTypeAutoDeployEnabled           ServiceEventType = "auto_deploy_enabled"
	ServiceEventTypeAutoscalingConfigChanged    ServiceEventType = "autoscaling_config_changed"
	ServiceEventTypeAutoscalingEnded            ServiceEventType = "autoscaling_ended"
	ServiceEventTypeAutoscalingStarted          ServiceEventType = "autoscaling_started"
	ServiceEventTypeBranchDeleted               ServiceEventType = "branch_deleted"
	ServiceEventTypeBuildEnded                  ServiceEventType = "build_ended"
	ServiceEventTypeBuildStarted                ServiceEventType = "build_started"
	ServiceEventTypeCommitIgnored               ServiceEventType = "commit_ignored"
	ServiceEventTypeCronJobRunEnded             ServiceEventType = "cron_job_run_ended"
	ServiceEventTypeCronJobRunStarted           ServiceEventType = "cron_job_run_started"
	ServiceEventTypeDeployEnded                 ServiceEventType = "deploy_ended"
	ServiceEventTypeDeployStarted               ServiceEventType = "deploy_started"
	ServiceEventTypeDiskCreated                 ServiceEventType = "disk_created"
	ServiceEventTypeDiskDeleted                 ServiceEventType = "disk_deleted"
	ServiceEventTypeDiskUpdated                 ServiceEventType = "disk_updated"
	ServiceEventTypeImagePullFailed             ServiceEventType = "image_pull_failed"
	ServiceEventTypeInitialDeployHookEnded      ServiceEventType = "initial_deploy_hook_ended"
	ServiceEventTypeInitialDeployHookStarted    ServiceEventType = "initial_deploy_hook_started"
	ServiceEventTypeInstanceCountChanged        ServiceEventType = "instance_count_changed"
	ServiceEventTypeJobRunEnded                 ServiceEventType = "job_run_ended"
	ServiceEventTypeMaintenanceEnded            ServiceEventType = "maintenance_ended"
	ServiceEventTypeMaintenanceModeEnabled      ServiceEventType = "maintenance_mode_enabled"
	ServiceEventTypeMaintenanceModeUriUpdated   ServiceEventType = "maintenance_mode_uri_updated"
	ServiceEventTypeMaintenanceStarted          ServiceEventType = "maintenance_started"
	ServiceEventTypePipelineMinutesExhausted    ServiceEventType = "pipeline_minutes_exhausted"
	ServiceEventTypePlanChanged                 ServiceEventType = "plan_changed"
	ServiceEventTypePreDeployEnded              ServiceEventType = "pre_deploy_ended"
	ServiceEventTypePreDeployStarted            ServiceEventType = "pre_deploy_started"
	ServiceEventTypeServerAvailable             ServiceEventType = "server_available"
	ServiceEventTypeServerFailed                ServiceEventType = "server_failed"
	ServiceEventTypeServerHardwareFailure       ServiceEventType = "server_hardware_failure"
	ServiceEventTypeServerRestarted             ServiceEventType = "server_restarted"
	ServiceEventTypeServiceResumed              ServiceEventType = "service_resumed"
	ServiceEventTypeServiceSuspended            ServiceEventType = "service_suspended"
	ServiceEventTypeSuspenderAdded              ServiceEventType = "suspender_added"
	ServiceEventTypeSuspenderRemoved            ServiceEventType = "suspender_removed"
	ServiceEventTypeZeroDowntimeRedeployEnded   ServiceEventType = "zero_downtime_redeploy_ended"
	ServiceEventTypeZeroDowntimeRedeployStarted ServiceEventType = "zero_downtime_redeploy_started"
)

// Valid indicates whether the value is a known member of the ServiceEventType enum.
func (e ServiceEventType) Valid() bool {
	switch e {
	case ServiceEventTypeAutoDeployDisabled:
		return true
	case ServiceEventTypeAutoDeployEnabled:
		return true
	case ServiceEventTypeAutoscalingConfigChanged:
		return true
	case ServiceEventTypeAutoscalingEnded:
		return true
	case ServiceEventTypeAutoscalingStarted:
		return true
	case ServiceEventTypeBranchDeleted:
		return true
	case ServiceEventTypeBuildEnded:
		return true
	case ServiceEventTypeBuildStarted:
		return true
	case ServiceEventTypeCommitIgnored:
		return true
	case ServiceEventTypeCronJobRunEnded:
		return true
	case ServiceEventTypeCronJobRunStarted:
		return true
	case ServiceEventTypeDeployEnded:
		return true
	case ServiceEventTypeDeployStarted:
		return true
	case ServiceEventTypeDiskCreated:
		return true
	case ServiceEventTypeDiskDeleted:
		return true
	case ServiceEventTypeDiskUpdated:
		return true
	case ServiceEventTypeImagePullFailed:
		return true
	case ServiceEventTypeInitialDeployHookEnded:
		return true
	case ServiceEventTypeInitialDeployHookStarted:
		return true
	case ServiceEventTypeInstanceCountChanged:
		return true
	case ServiceEventTypeJobRunEnded:
		return true
	case ServiceEventTypeMaintenanceEnded:
		return true
	case ServiceEventTypeMaintenanceModeEnabled:
		return true
	case ServiceEventTypeMaintenanceModeUriUpdated:
		return true
	case ServiceEventTypeMaintenanceStarted:
		return true
	case ServiceEventTypePipelineMinutesExhausted:
		return true
	case ServiceEventTypePlanChanged:
		return true
	case ServiceEventTypePreDeployEnded:
		return true
	case ServiceEventTypePreDeployStarted:
		return true
	case ServiceEventTypeServerAvailable:
		return true
	case ServiceEventTypeServerFailed:
		return true
	case ServiceEventTypeServerHardwareFailure:
		return true
	case ServiceEventTypeServerRestarted:
		return true
	case ServiceEventTypeServiceResumed:
		return true
	case ServiceEventTypeServiceSuspended:
		return true
	case ServiceEventTypeSuspenderAdded:
		return true
	case ServiceEventTypeSuspenderRemoved:
		return true
	case ServiceEventTypeZeroDowntimeRedeployEnded:
		return true
	case ServiceEventTypeZeroDowntimeRedeployStarted:
		return true
	default:
		return false
	}
}

// EventType defines model for eventType.
type EventType string

// ServiceEventType defines model for serviceEventType.
type ServiceEventType string
