// Package autoscaling provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package autoscaling

// AutoscalingConfig defines model for autoscalingConfig.
type AutoscalingConfig struct {
	Criteria AutoscalingCriteria `json:"criteria"`
	Enabled  bool                `json:"enabled"`

	// Max The maximum number of instances for the service
	Max int `json:"max"`

	// Min The minimum number of instances for the service
	Min int `json:"min"`
}

// AutoscalingCriteria defines model for autoscalingCriteria.
type AutoscalingCriteria struct {
	Cpu    AutoscalingCriteriaPercentage `json:"cpu"`
	Memory AutoscalingCriteriaPercentage `json:"memory"`
}

// AutoscalingCriteriaPercentage defines model for autoscalingCriteriaPercentage.
type AutoscalingCriteriaPercentage struct {
	Enabled bool `json:"enabled"`

	// Percentage Determines when your service will be scaled. If the average resource utilization is significantly above/below the target, we will increase/decrease the number of instances.
	Percentage int `json:"percentage"`
}
