// Package metrics provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package metrics

import (
	"time"
)

// Defines values for FilterApplicationValuesCollectionFilter.
const (
	Instance FilterApplicationValuesCollectionFilter = "instance"
)

// Defines values for FilterHTTPValuesCollectionFilter.
const (
	FilterHTTPValuesCollectionFilterHost       FilterHTTPValuesCollectionFilter = "host"
	FilterHTTPValuesCollectionFilterStatusCode FilterHTTPValuesCollectionFilter = "statusCode"
)

// Defines values for ApplicationMetricAggregationMethod.
const (
	AVG ApplicationMetricAggregationMethod = "AVG"
	MAX ApplicationMetricAggregationMethod = "MAX"
	MIN ApplicationMetricAggregationMethod = "MIN"
)

// Defines values for HttpAggregateBy.
const (
	HttpAggregateByHost       HttpAggregateBy = "host"
	HttpAggregateByStatusCode HttpAggregateBy = "statusCode"
)

// FilterApplicationValuesCollection A collection of filter values for application metrics
type FilterApplicationValuesCollection = []struct {
	Filter *FilterApplicationValuesCollectionFilter `json:"filter,omitempty"`
	Values *[]string                                `json:"values,omitempty"`
}

// FilterApplicationValuesCollectionFilter defines model for FilterApplicationValuesCollection.Filter.
type FilterApplicationValuesCollectionFilter string

// FilterHTTPValuesCollection A collection of filter values for HTTP metrics
type FilterHTTPValuesCollection = []struct {
	Filter *FilterHTTPValuesCollectionFilter `json:"filter,omitempty"`
	Values *[]string                         `json:"values,omitempty"`
}

// FilterHTTPValuesCollectionFilter defines model for FilterHTTPValuesCollection.Filter.
type FilterHTTPValuesCollectionFilter string

// FilterPathValuesCollection A collection of suggested paths to filter by
type FilterPathValuesCollection = []string

// Label A time series datapoint label
type Label struct {
	Field string `json:"field"`
	Value string `json:"value"`
}

// TimeSeries A time series data point
type TimeSeries struct {
	// Labels List of labels describing the time series
	Labels []Label `json:"labels"`
	Unit   Unit    `json:"unit"`

	// Values The values of the time series
	Values []TimeSeriesValue `json:"values"`
}

// TimeSeriesCollection A collection of time series
type TimeSeriesCollection = []TimeSeries

// TimeSeriesValue A time series datapoint value
type TimeSeriesValue struct {
	Timestamp time.Time `json:"timestamp"`
	Value     float32   `json:"value"`
}

// Unit defines model for unit.
type Unit = string

// ApplicationMetricAggregationMethod defines model for applicationMetricAggregationMethod.
type ApplicationMetricAggregationMethod string

// DatastoreResourceQueryParam defines model for datastoreResourceQueryParam.
type DatastoreResourceQueryParam = string

// HostQueryParam defines model for hostQueryParam.
type HostQueryParam = string

// HttpAggregateBy defines model for httpAggregateBy.
type HttpAggregateBy string

// HttpStatusCode defines model for httpStatusCode.
type HttpStatusCode = string

// InstanceQueryParam defines model for instanceQueryParam.
type InstanceQueryParam = string

// PathQueryParam defines model for pathQueryParam.
type PathQueryParam = string

// PostgresResourceQueryParam defines model for postgresResourceQueryParam.
type PostgresResourceQueryParam = string

// Quantile defines model for quantile.
type Quantile = float32

// ResolutionParam defines model for resolutionParam.
type ResolutionParam = float32

// ResourceQueryParam defines model for resourceQueryParam.
type ResourceQueryParam = string

// ServiceQueryParam defines model for serviceQueryParam.
type ServiceQueryParam = string

// ServiceResourceQueryParam defines model for serviceResourceQueryParam.
type ServiceResourceQueryParam = string

// Metrics200Response A collection of time series
type Metrics200Response = TimeSeriesCollection

// MetricsFiltersApplication200Response A collection of filter values for application metrics
type MetricsFiltersApplication200Response = FilterApplicationValuesCollection

// MetricsFiltersHTTP200Response A collection of filter values for HTTP metrics
type MetricsFiltersHTTP200Response = FilterHTTPValuesCollection

// MetricsFiltersPath200Response A collection of suggested paths to filter by
type MetricsFiltersPath200Response = FilterPathValuesCollection
