// Package maintenance provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package maintenance

import (
	"time"
)

// Defines values for MaintenanceState.
const (
	Cancelled       MaintenanceState = "cancelled"
	Failed          MaintenanceState = "failed"
	InProgress      MaintenanceState = "in_progress"
	Scheduled       MaintenanceState = "scheduled"
	Succeeded       MaintenanceState = "succeeded"
	UserFixRequired MaintenanceState = "user_fix_required"
)

// MaintenanceResourceId The Id of a resource that can undergo maintenance (Id of a service, a Postgres instance, or a Redis instance)
type MaintenanceResourceId = string

// MaintenanceRun defines model for maintenanceRun.
type MaintenanceRun struct {
	Id MaintenanceRunId `json:"id"`

	// PendingMaintenanceBy If present, the maintenance run cannot be scheduled for later than this date-time.
	PendingMaintenanceBy *time.Time       `json:"pendingMaintenanceBy,omitempty"`
	ScheduledAt          time.Time        `json:"scheduledAt"`
	State                MaintenanceState `json:"state"`
	Type                 string           `json:"type"`
}

// MaintenanceRunId defines model for maintenanceRunId.
type MaintenanceRunId = string

// MaintenanceRunPATCH defines model for maintenanceRunPATCH.
type MaintenanceRunPATCH struct {
	// ScheduledAt The date-time at which the maintenance is scheduled to start. This must be before the pendingMaintenanceBy date-time.
	ScheduledAt *time.Time `json:"scheduledAt,omitempty"`
}

// MaintenanceRunWithResource defines model for maintenanceRunWithResource.
type MaintenanceRunWithResource struct {
	Id MaintenanceRunId `json:"id"`

	// PendingMaintenanceBy If present, the maintenance run cannot be scheduled for later than this date-time.
	PendingMaintenanceBy *time.Time `json:"pendingMaintenanceBy,omitempty"`

	// ResourceId The Id of a resource that can undergo maintenance (Id of a service, a Postgres instance, or a Redis instance)
	ResourceId  MaintenanceResourceId `json:"resourceId"`
	ScheduledAt time.Time             `json:"scheduledAt"`
	State       MaintenanceState      `json:"state"`
	Type        string                `json:"type"`
}

// MaintenanceState defines model for maintenanceState.
type MaintenanceState string

// MaintenanceResourcesParam defines model for maintenanceResourcesParam.
type MaintenanceResourcesParam = []MaintenanceResourceId

// MaintenanceRunParam defines model for maintenanceRunParam.
type MaintenanceRunParam = MaintenanceRunId

// MaintenanceStateParam defines model for maintenanceStateParam.
type MaintenanceStateParam = []MaintenanceState
