// Package workflows provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package workflows

import (
	"time"
)

// BuildConfig defines model for BuildConfig.
type BuildConfig struct {
	// Branch The branch to use for the build, if applicable.
	Branch *string `json:"branch,omitempty"`

	// BuildCommand The command to run to build the workflow.
	BuildCommand string `json:"buildCommand"`

	// Repo The repository URL to use for the build.
	Repo string `json:"repo"`

	// RootDir The root directory of the repository to use for the build, if applicable.
	RootDir *string `json:"rootDir,omitempty"`

	// Runtime The runtime environment for the workflow (e.g., node, python, etc.).
	Runtime Runtime `json:"runtime"`
}

// Image defines model for Image.
type Image struct {
	// ImagePath Path to the image used for this server (e.g docker.io/library/nginx:latest).
	ImagePath string `json:"imagePath"`

	// RegistryCredentialId Optional reference to the registry credential passed to the image repository to retrieve this image.
	RegistryCredentialId *string `json:"registryCredentialId,omitempty"`
}

// ImageVersion defines model for ImageVersion.
type ImageVersion struct {
	// ImagePath Path to the image used for this server (e.g docker.io/library/nginx:latest).
	ImagePath string `json:"imagePath"`

	// RegistryCredentialId Optional reference to the registry credential passed to the image repository to retrieve this image.
	RegistryCredentialId *string `json:"registryCredentialId,omitempty"`

	// Sha SHA that the image reference was resolved to when creating the workflow version.
	Sha string `json:"sha"`
}

// Runtime The runtime environment for the workflow (e.g., node, python, etc.).
type Runtime = string

// Workflow defines model for Workflow.
type Workflow struct {
	BuildConfig *BuildConfig `json:"buildConfig,omitempty"`
	CreatedAt   time.Time    `json:"createdAt"`
	Id          string       `json:"id"`
	Image       *Image       `json:"image,omitempty"`
	Name        string       `json:"name"`
	OwnerId     string       `json:"ownerId"`

	// RunCommand The command to run the workflow
	RunCommand *string   `json:"runCommand,omitempty"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

// WorkflowCreate defines model for WorkflowCreate.
type WorkflowCreate struct {
	BuildConfig *BuildConfig `json:"buildConfig,omitempty"`
	Image       *Image       `json:"image,omitempty"`
	Name        string       `json:"name"`
	OwnerId     string       `json:"ownerId"`

	// RunCommand The command to run the workflow
	RunCommand *string `json:"runCommand,omitempty"`
}

// WorkflowUpdate defines model for WorkflowUpdate.
type WorkflowUpdate struct {
	BuildConfig *BuildConfig `json:"buildConfig,omitempty"`
	Image       *Image       `json:"image,omitempty"`
	Name        *string      `json:"name,omitempty"`

	// RunCommand The command to run the workflow
	RunCommand *string `json:"runCommand,omitempty"`
}

// WorkflowVersion defines model for WorkflowVersion.
type WorkflowVersion struct {
	CreatedAt  time.Time    `json:"createdAt"`
	Id         string       `json:"id"`
	Image      ImageVersion `json:"image"`
	Name       string       `json:"name"`
	WorkflowId string       `json:"workflowId"`
}

// WorkflowIDParam defines model for WorkflowIDParam.
type WorkflowIDParam = string

// WorkflowVersionIDParam defines model for WorkflowVersionIDParam.
type WorkflowVersionIDParam = string
