// Package workflows provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package workflows

import (
	"encoding/json"
	"time"

	externalRef4 "terraform-provider-render/internal/client/envvar"

	"github.com/oapi-codegen/runtime"
)

// Defines values for AutoDeployTrigger.
const (
	ChecksPass AutoDeployTrigger = "checksPass"
	Commit     AutoDeployTrigger = "commit"
	Off        AutoDeployTrigger = "off"
)

// Defines values for Region.
const (
	Frankfurt Region = "frankfurt"
	Ohio      Region = "ohio"
	Oregon    Region = "oregon"
	Singapore Region = "singapore"
	Virginia  Region = "virginia"
)

// Defines values for Runtime.
const (
	Elixir Runtime = "elixir"
	Go     Runtime = "go"
	Node   Runtime = "node"
	Python Runtime = "python"
	Ruby   Runtime = "ruby"
)

// Defines values for TaskRunStatus.
const (
	Canceled  TaskRunStatus = "canceled"
	Completed TaskRunStatus = "completed"
	Failed    TaskRunStatus = "failed"
	Paused    TaskRunStatus = "paused"
	Pending   TaskRunStatus = "pending"
	Running   TaskRunStatus = "running"
	Succeeded TaskRunStatus = "succeeded"
)

// Defines values for WorkflowVersionStatus.
const (
	BuildFailed        WorkflowVersionStatus = "build_failed"
	Building           WorkflowVersionStatus = "building"
	Created            WorkflowVersionStatus = "created"
	Ready              WorkflowVersionStatus = "ready"
	Registering        WorkflowVersionStatus = "registering"
	RegistrationFailed WorkflowVersionStatus = "registration_failed"
)

// AutoDeployTrigger Controls autodeploy behavior. "commit" deploys when a commit is pushed to the branch. "checksPass" waits for CI checks to pass before deploying. "off" disables autodeploy.
type AutoDeployTrigger string

// BuildConfig defines model for BuildConfig.
type BuildConfig struct {
	// Branch The branch to use for the build, if applicable.
	Branch *string `json:"branch,omitempty"`

	// BuildCommand The command to run to build the workflow.
	BuildCommand string `json:"buildCommand"`

	// Repo The repository URL to use for the build.
	Repo string `json:"repo"`

	// RootDir The root directory of the repository to use for the build, if applicable.
	RootDir *string `json:"rootDir,omitempty"`

	// Runtime The runtime environment for the workflow (e.g., node, python, etc.).
	Runtime Runtime `json:"runtime"`
}

// CreateVersion defines model for CreateVersion.
type CreateVersion struct {
	Commit     *string `json:"commit,omitempty"`
	WorkflowId string  `json:"workflowId"`
}

// Image defines model for Image.
type Image struct {
	// ImagePath Path to the image used for this server (e.g docker.io/library/nginx:latest).
	ImagePath string `json:"imagePath"`

	// RegistryCredentialId Optional reference to the registry credential passed to the image repository to retrieve this image.
	RegistryCredentialId *string `json:"registryCredentialId,omitempty"`
}

// ImageVersion defines model for ImageVersion.
type ImageVersion struct {
	// ImagePath Path to the image used for this server (e.g docker.io/library/nginx:latest).
	ImagePath string `json:"imagePath"`

	// RegistryCredentialId Optional reference to the registry credential passed to the image repository to retrieve this image.
	RegistryCredentialId *string `json:"registryCredentialId,omitempty"`

	// Sha SHA that the image reference was resolved to when creating the workflow version.
	Sha string `json:"sha"`
}

// Region Defaults to "oregon"
type Region string

// RunTask defines model for RunTask.
type RunTask struct {
	// Input Input data for a task. Can be either an array (for positional arguments) or an object (for named parameters).
	Input TaskData `json:"input"`

	// Task A task slug in the format workflow-slug/task-name. An optional version can be appended (workflow-slug/task-name:version). If no version is provided, the latest version is used.
	Task TaskSlug `json:"task"`
}

// Runtime The runtime environment for the workflow (e.g., node, python, etc.).
type Runtime string

// Task defines model for Task.
type Task struct {
	CreatedAt         time.Time `json:"createdAt"`
	Id                string    `json:"id"`
	Name              string    `json:"name"`
	WorkflowId        *string   `json:"workflowId,omitempty"`
	WorkflowVersionId *string   `json:"workflowVersionId,omitempty"`
}

// TaskAttempt defines model for TaskAttempt.
type TaskAttempt struct {
	CompletedAt *time.Time    `json:"completedAt,omitempty"`
	EnqueuedAt  *time.Time    `json:"enqueuedAt,omitempty"`
	StartedAt   time.Time     `json:"startedAt"`
	Status      TaskRunStatus `json:"status"`
}

// TaskAttemptDetails defines model for TaskAttemptDetails.
type TaskAttemptDetails struct {
	CompletedAt *time.Time `json:"completedAt,omitempty"`
	EnqueuedAt  *time.Time `json:"enqueuedAt,omitempty"`

	// Error Error message if the task attempt failed.
	Error     *string        `json:"error,omitempty"`
	Results   *TaskRunResult `json:"results,omitempty"`
	StartedAt time.Time      `json:"startedAt"`
	Status    TaskRunStatus  `json:"status"`
}

// TaskData Input data for a task. Can be either an array (for positional arguments) or an object (for named parameters).
type TaskData struct {
	union json.RawMessage
}

// TaskData0 Positional arguments passed to the task function
type TaskData0 = []interface{}

// TaskData1 Named parameters passed to the task function as keyword arguments
type TaskData1 map[string]interface{}

// TaskRun defines model for TaskRun.
type TaskRun struct {
	Attempts        []TaskAttempt `json:"attempts"`
	CompletedAt     *time.Time    `json:"completedAt,omitempty"`
	Id              string        `json:"id"`
	ParentTaskRunId string        `json:"parentTaskRunId"`
	Retries         int           `json:"retries"`
	RootTaskRunId   string        `json:"rootTaskRunId"`
	StartedAt       *time.Time    `json:"startedAt,omitempty"`
	Status          TaskRunStatus `json:"status"`
	TaskId          string        `json:"taskId"`
}

// TaskRunDetails defines model for TaskRunDetails.
type TaskRunDetails struct {
	Attempts    []TaskAttemptDetails `json:"attempts"`
	CompletedAt *time.Time           `json:"completedAt,omitempty"`

	// Error Error message if the task run failed.
	Error *string `json:"error,omitempty"`
	Id    string  `json:"id"`

	// Input Input data for a task. Can be either an array (for positional arguments) or an object (for named parameters).
	Input           TaskData      `json:"input"`
	ParentTaskRunId string        `json:"parentTaskRunId"`
	Results         TaskRunResult `json:"results"`
	Retries         int           `json:"retries"`
	RootTaskRunId   string        `json:"rootTaskRunId"`
	StartedAt       *time.Time    `json:"startedAt,omitempty"`
	Status          TaskRunStatus `json:"status"`
	TaskId          string        `json:"taskId"`
}

// TaskRunResult defines model for TaskRunResult.
type TaskRunResult = []interface{}

// TaskRunStatus defines model for TaskRunStatus.
type TaskRunStatus string

// TaskSlug A task slug in the format workflow-slug/task-name. An optional version can be appended (workflow-slug/task-name:version). If no version is provided, the latest version is used.
type TaskSlug = string

// Workflow defines model for Workflow.
type Workflow struct {
	// AutoDeployTrigger Controls autodeploy behavior. "commit" deploys when a commit is pushed to the branch. "checksPass" waits for CI checks to pass before deploying. "off" disables autodeploy.
	AutoDeployTrigger *AutoDeployTrigger `json:"autoDeployTrigger,omitempty"`
	BuildConfig       BuildConfig        `json:"buildConfig"`
	CreatedAt         time.Time          `json:"createdAt"`
	EnvironmentId     *string            `json:"environmentId,omitempty"`
	Id                string             `json:"id"`
	Name              string             `json:"name"`
	OwnerId           string             `json:"ownerId"`

	// Region Defaults to "oregon"
	Region Region `json:"region"`

	// RunCommand Command to run the workflow.
	RunCommand string    `json:"runCommand"`
	Slug       *string   `json:"slug,omitempty"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

// WorkflowCreate defines model for WorkflowCreate.
type WorkflowCreate struct {
	// AutoDeployTrigger Controls autodeploy behavior. "commit" deploys when a commit is pushed to the branch. "checksPass" waits for CI checks to pass before deploying. "off" disables autodeploy.
	AutoDeployTrigger *AutoDeployTrigger             `json:"autoDeployTrigger,omitempty"`
	BuildConfig       BuildConfig                    `json:"buildConfig"`
	EnvVars           *externalRef4.EnvVarInputArray `json:"envVars,omitempty"`
	Name              string                         `json:"name"`
	OwnerId           string                         `json:"ownerId"`

	// Region Defaults to "oregon"
	Region Region `json:"region"`

	// RunCommand The command to run the workflow
	RunCommand string `json:"runCommand"`
}

// WorkflowUpdate defines model for WorkflowUpdate.
type WorkflowUpdate struct {
	// AutoDeployTrigger Controls autodeploy behavior. "commit" deploys when a commit is pushed to the branch. "checksPass" waits for CI checks to pass before deploying. "off" disables autodeploy.
	AutoDeployTrigger *AutoDeployTrigger `json:"autoDeployTrigger,omitempty"`
	BuildConfig       *BuildConfig       `json:"buildConfig,omitempty"`
	Name              *string            `json:"name,omitempty"`

	// RunCommand The command to run the workflow
	RunCommand *string `json:"runCommand,omitempty"`
}

// WorkflowVersion defines model for WorkflowVersion.
type WorkflowVersion struct {
	CreatedAt  time.Time             `json:"createdAt"`
	Id         string                `json:"id"`
	Name       string                `json:"name"`
	Status     WorkflowVersionStatus `json:"status"`
	WorkflowId string                `json:"workflowId"`
}

// WorkflowVersionStatus defines model for WorkflowVersionStatus.
type WorkflowVersionStatus string

// RootTaskRunIDFilterParam defines model for RootTaskRunIDFilterParam.
type RootTaskRunIDFilterParam = []string

// TaskIDParam defines model for TaskIDParam.
type TaskIDParam = string

// TaskRunIDParam defines model for TaskRunIDParam.
type TaskRunIDParam = string

// TaskSlugFilterParam defines model for TaskSlugFilterParam.
type TaskSlugFilterParam = []string

// WorkflowIDFilterParam defines model for WorkflowIDFilterParam.
type WorkflowIDFilterParam = []string

// WorkflowIDParam defines model for WorkflowIDParam.
type WorkflowIDParam = string

// WorkflowVersionIDFilterParam defines model for WorkflowVersionIDFilterParam.
type WorkflowVersionIDFilterParam = []string

// WorkflowVersionIDParam defines model for WorkflowVersionIDParam.
type WorkflowVersionIDParam = string

// AsTaskData0 returns the union data inside the TaskData as a TaskData0
func (t TaskData) AsTaskData0() (TaskData0, error) {
	var body TaskData0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTaskData0 overwrites any union data inside the TaskData as the provided TaskData0
func (t *TaskData) FromTaskData0(v TaskData0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTaskData0 performs a merge with any union data inside the TaskData, using the provided TaskData0
func (t *TaskData) MergeTaskData0(v TaskData0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTaskData1 returns the union data inside the TaskData as a TaskData1
func (t TaskData) AsTaskData1() (TaskData1, error) {
	var body TaskData1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTaskData1 overwrites any union data inside the TaskData as the provided TaskData1
func (t *TaskData) FromTaskData1(v TaskData1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTaskData1 performs a merge with any union data inside the TaskData, using the provided TaskData1
func (t *TaskData) MergeTaskData1(v TaskData1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t TaskData) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *TaskData) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
