// Package workflows provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package workflows

import (
	"time"
)

// Defines values for Region.
const (
	Frankfurt Region = "frankfurt"
	Ohio      Region = "ohio"
	Oregon    Region = "oregon"
	Singapore Region = "singapore"
	Virginia  Region = "virginia"
)

// Defines values for Runtime.
const (
	Elixir Runtime = "elixir"
	Go     Runtime = "go"
	Node   Runtime = "node"
	Python Runtime = "python"
	Ruby   Runtime = "ruby"
)

// Defines values for TaskRunStatus.
const (
	Canceled  TaskRunStatus = "canceled"
	Completed TaskRunStatus = "completed"
	Failed    TaskRunStatus = "failed"
	Pending   TaskRunStatus = "pending"
	Running   TaskRunStatus = "running"
)

// Defines values for WorkflowVersionStatus.
const (
	BuildFailed        WorkflowVersionStatus = "build_failed"
	Building           WorkflowVersionStatus = "building"
	Created            WorkflowVersionStatus = "created"
	Ready              WorkflowVersionStatus = "ready"
	Registering        WorkflowVersionStatus = "registering"
	RegistrationFailed WorkflowVersionStatus = "registration_failed"
)

// BuildConfig defines model for BuildConfig.
type BuildConfig struct {
	// Branch The branch to use for the build, if applicable.
	Branch *string `json:"branch,omitempty"`

	// BuildCommand The command to run to build the workflow.
	BuildCommand string `json:"buildCommand"`

	// Repo The repository URL to use for the build.
	Repo string `json:"repo"`

	// RootDir The root directory of the repository to use for the build, if applicable.
	RootDir *string `json:"rootDir,omitempty"`

	// Runtime The runtime environment for the workflow (e.g., node, python, etc.).
	Runtime Runtime `json:"runtime"`
}

// CreateVersion defines model for CreateVersion.
type CreateVersion struct {
	Commit     *string `json:"commit,omitempty"`
	WorkflowId string  `json:"workflowId"`
}

// Image defines model for Image.
type Image struct {
	// ImagePath Path to the image used for this server (e.g docker.io/library/nginx:latest).
	ImagePath string `json:"imagePath"`

	// RegistryCredentialId Optional reference to the registry credential passed to the image repository to retrieve this image.
	RegistryCredentialId *string `json:"registryCredentialId,omitempty"`
}

// ImageVersion defines model for ImageVersion.
type ImageVersion struct {
	// ImagePath Path to the image used for this server (e.g docker.io/library/nginx:latest).
	ImagePath string `json:"imagePath"`

	// RegistryCredentialId Optional reference to the registry credential passed to the image repository to retrieve this image.
	RegistryCredentialId *string `json:"registryCredentialId,omitempty"`

	// Sha SHA that the image reference was resolved to when creating the workflow version.
	Sha string `json:"sha"`
}

// Region Defaults to "oregon"
type Region string

// RunTask defines model for RunTask.
type RunTask struct {
	Input TaskData `json:"input"`

	// Task Either a task ID or a workflow slug with task name and optional version name. If a version is not provided, the latest version of the task will be used.
	Task TaskIdentifier `json:"task"`
}

// Runtime The runtime environment for the workflow (e.g., node, python, etc.).
type Runtime string

// Task defines model for Task.
type Task struct {
	CreatedAt         time.Time `json:"createdAt"`
	Id                string    `json:"id"`
	Name              string    `json:"name"`
	WorkflowId        *string   `json:"workflowId,omitempty"`
	WorkflowVersionId *string   `json:"workflowVersionId,omitempty"`
}

// TaskData defines model for TaskData.
type TaskData = []interface{}

// TaskIdentifier Either a task ID or a workflow slug with task name and optional version name. If a version is not provided, the latest version of the task will be used.
type TaskIdentifier = string

// TaskRun defines model for TaskRun.
type TaskRun struct {
	CompletedAt     *time.Time    `json:"completedAt,omitempty"`
	Id              string        `json:"id"`
	ParentTaskRunId string        `json:"parentTaskRunId"`
	Retries         int           `json:"retries"`
	RootTaskRunId   string        `json:"rootTaskRunId"`
	StartedAt       *time.Time    `json:"startedAt,omitempty"`
	Status          TaskRunStatus `json:"status"`
	TaskId          string        `json:"taskId"`
}

// TaskRunDetails defines model for TaskRunDetails.
type TaskRunDetails struct {
	CompletedAt *time.Time `json:"completedAt,omitempty"`

	// Error Error message if the task run failed.
	Error           *string       `json:"error,omitempty"`
	Id              string        `json:"id"`
	Input           TaskData      `json:"input"`
	ParentTaskRunId string        `json:"parentTaskRunId"`
	Results         TaskRunResult `json:"results"`
	Retries         int           `json:"retries"`
	RootTaskRunId   string        `json:"rootTaskRunId"`
	StartedAt       *time.Time    `json:"startedAt,omitempty"`
	Status          TaskRunStatus `json:"status"`
	TaskId          string        `json:"taskId"`
}

// TaskRunResult defines model for TaskRunResult.
type TaskRunResult = []interface{}

// TaskRunStatus defines model for TaskRunStatus.
type TaskRunStatus string

// TaskSlug defines model for TaskSlug.
type TaskSlug struct {
	TaskName            string  `json:"taskName"`
	Version             *string `json:"version,omitempty"`
	WorkflowServiceSlug string  `json:"workflowServiceSlug"`
}

// Workflow defines model for Workflow.
type Workflow struct {
	BuildConfig   BuildConfig `json:"buildConfig"`
	CreatedAt     time.Time   `json:"createdAt"`
	EnvironmentId *string     `json:"environmentId,omitempty"`
	Id            string      `json:"id"`
	Name          string      `json:"name"`
	OwnerId       string      `json:"ownerId"`

	// Region Defaults to "oregon"
	Region Region `json:"region"`

	// RunCommand Command to run the workflow.
	RunCommand string    `json:"runCommand"`
	Slug       *string   `json:"slug,omitempty"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

// WorkflowCreate defines model for WorkflowCreate.
type WorkflowCreate struct {
	BuildConfig BuildConfig `json:"buildConfig"`
	Name        string      `json:"name"`
	OwnerId     string      `json:"ownerId"`

	// Region Defaults to "oregon"
	Region Region `json:"region"`

	// RunCommand The command to run the workflow
	RunCommand string `json:"runCommand"`
}

// WorkflowUpdate defines model for WorkflowUpdate.
type WorkflowUpdate struct {
	BuildConfig *BuildConfig `json:"buildConfig,omitempty"`
	Name        *string      `json:"name,omitempty"`

	// RunCommand The command to run the workflow
	RunCommand *string `json:"runCommand,omitempty"`
}

// WorkflowVersion defines model for WorkflowVersion.
type WorkflowVersion struct {
	CreatedAt  time.Time             `json:"createdAt"`
	Id         string                `json:"id"`
	Name       string                `json:"name"`
	Status     WorkflowVersionStatus `json:"status"`
	WorkflowId string                `json:"workflowId"`
}

// WorkflowVersionStatus defines model for WorkflowVersionStatus.
type WorkflowVersionStatus string

// RootTaskRunIDFilterParam defines model for RootTaskRunIDFilterParam.
type RootTaskRunIDFilterParam = []string

// TaskIDParam defines model for TaskIDParam.
type TaskIDParam = string

// TaskIdFilterParam defines model for TaskIdFilterParam.
type TaskIdFilterParam = []string

// TaskRunIDParam defines model for TaskRunIDParam.
type TaskRunIDParam = string

// WorkflowIDFilterParam defines model for WorkflowIDFilterParam.
type WorkflowIDFilterParam = []string

// WorkflowIDParam defines model for WorkflowIDParam.
type WorkflowIDParam = string

// WorkflowVersionIDFilterParam defines model for WorkflowVersionIDFilterParam.
type WorkflowVersionIDFilterParam = []string

// WorkflowVersionIDParam defines model for WorkflowVersionIDParam.
type WorkflowVersionIDParam = string
