// Package envvar provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package envvar

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

// EnvVarInput defines model for envVarInput.
type EnvVarInput struct {
	union json.RawMessage
}

// EnvVarInputArray defines model for envVarInputArray.
type EnvVarInputArray = []EnvVarInput

// EnvVarKeyGenerateValue defines model for envVarKeyGenerateValue.
type EnvVarKeyGenerateValue struct {
	// GenerateValue If true, Render generates a strong random value for this environment variable on creation. Cannot be combined with `value`.
	GenerateValue bool   `json:"generateValue"`
	Key           string `json:"key"`
}

// EnvVarKeyValue defines model for envVarKeyValue.
type EnvVarKeyValue struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// AsEnvVarKeyValue returns the union data inside the EnvVarInput as a EnvVarKeyValue
func (t EnvVarInput) AsEnvVarKeyValue() (EnvVarKeyValue, error) {
	var body EnvVarKeyValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEnvVarKeyValue overwrites any union data inside the EnvVarInput as the provided EnvVarKeyValue
func (t *EnvVarInput) FromEnvVarKeyValue(v EnvVarKeyValue) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEnvVarKeyValue performs a merge with any union data inside the EnvVarInput, using the provided EnvVarKeyValue
func (t *EnvVarInput) MergeEnvVarKeyValue(v EnvVarKeyValue) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEnvVarKeyGenerateValue returns the union data inside the EnvVarInput as a EnvVarKeyGenerateValue
func (t EnvVarInput) AsEnvVarKeyGenerateValue() (EnvVarKeyGenerateValue, error) {
	var body EnvVarKeyGenerateValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEnvVarKeyGenerateValue overwrites any union data inside the EnvVarInput as the provided EnvVarKeyGenerateValue
func (t *EnvVarInput) FromEnvVarKeyGenerateValue(v EnvVarKeyGenerateValue) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEnvVarKeyGenerateValue performs a merge with any union data inside the EnvVarInput, using the provided EnvVarKeyGenerateValue
func (t *EnvVarInput) MergeEnvVarKeyGenerateValue(v EnvVarKeyGenerateValue) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EnvVarInput) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EnvVarInput) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
