// Package jobs provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package jobs

import (
	"time"
)

// Defines values for JobStatus.
const (
	Canceled  JobStatus = "canceled"
	Failed    JobStatus = "failed"
	Pending   JobStatus = "pending"
	Running   JobStatus = "running"
	Succeeded JobStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the JobStatus enum.
func (e JobStatus) Valid() bool {
	switch e {
	case Canceled:
		return true
	case Failed:
		return true
	case Pending:
		return true
	case Running:
		return true
	case Succeeded:
		return true
	default:
		return false
	}
}

// Job defines model for job.
type Job struct {
	CreatedAt    time.Time  `json:"createdAt"`
	FinishedAt   *time.Time `json:"finishedAt,omitempty"`
	Id           JobId      `json:"id"`
	PlanId       string     `json:"planId"`
	ServiceId    string     `json:"serviceId"`
	StartCommand string     `json:"startCommand"`
	StartedAt    *time.Time `json:"startedAt,omitempty"`
	Status       *JobStatus `json:"status,omitempty"`
}

// JobId defines model for jobId.
type JobId = string

// JobStatus defines model for jobStatus.
type JobStatus string
