// Package jobs provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package jobs

import (
	"time"
)

// Defines values for JobStatus.
const (
	Canceled  JobStatus = "canceled"
	Failed    JobStatus = "failed"
	Pending   JobStatus = "pending"
	Running   JobStatus = "running"
	Succeeded JobStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the JobStatus enum.
func (e JobStatus) Valid() bool {
	switch e {
	case Canceled:
		return true
	case Failed:
		return true
	case Pending:
		return true
	case Running:
		return true
	case Succeeded:
		return true
	default:
		return false
	}
}

// Job defines model for job.
type Job struct {
	// CreatedAt Example: 2021-07-15T07:20:05.777035-07:00
	CreatedAt time.Time `json:"createdAt"`

	// FinishedAt Example: 2021-07-15T07:20:05.777035-07:00
	FinishedAt *time.Time `json:"finishedAt,omitempty"`

	// Id Example: job-cph1rs3idesc73a2b2mg
	Id JobId `json:"id"`

	// PlanId Example: plan-srv-004
	PlanId string `json:"planId"`

	// ServiceId Example: srv-xxxxx
	ServiceId string `json:"serviceId"`

	// StartCommand Example: echo 'hello world'
	StartCommand string `json:"startCommand"`

	// StartedAt Example: 2021-07-15T07:20:05.777035-07:00
	StartedAt *time.Time `json:"startedAt,omitempty"`
	Status    *JobStatus `json:"status,omitempty"`
}

// JobId Example: job-cph1rs3idesc73a2b2mg
type JobId = string

// JobStatus defines model for jobStatus.
type JobStatus string
