name: checks

on:
  push:
    branches:
      - main
  pull_request:

env:
  GIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'
      - name: Run tests
        run: TF_ACC=1 go test ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4.0
      - name: vet
        run: go vet ./...
      - name: lint
        run: golangci-lint run --timeout 10m
        env:
          GIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
