// Package eventstatuses provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package eventstatuses

// Defines values for CronJobRunStatus.
const (
	CronJobRunStatusCanceled     CronJobRunStatus = "canceled"
	CronJobRunStatusPending      CronJobRunStatus = "pending"
	CronJobRunStatusSuccessful   CronJobRunStatus = "successful"
	CronJobRunStatusUnsuccessful CronJobRunStatus = "unsuccessful"
)

// Valid indicates whether the value is a known member of the CronJobRunStatus enum.
func (e CronJobRunStatus) Valid() bool {
	switch e {
	case CronJobRunStatusCanceled:
		return true
	case CronJobRunStatusPending:
		return true
	case CronJobRunStatusSuccessful:
		return true
	case CronJobRunStatusUnsuccessful:
		return true
	default:
		return false
	}
}

// Defines values for EventStatus.
const (
	EventStatusCanceled  EventStatus = "canceled"
	EventStatusFailed    EventStatus = "failed"
	EventStatusSucceeded EventStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the EventStatus enum.
func (e EventStatus) Valid() bool {
	switch e {
	case EventStatusCanceled:
		return true
	case EventStatusFailed:
		return true
	case EventStatusSucceeded:
		return true
	default:
		return false
	}
}

// CronJobRunStatus defines model for cronJobRunStatus.
type CronJobRunStatus string

// EventStatus defines model for eventStatus.
type EventStatus string
